//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdtAEH
    {
        public string Empid { get; set; }
        public string EmpName { get; set; }
        public string Dept { get; set; }
        public string Img { get; set; }
        public string Section { get; set; }
        public string Stat { get; set; }
        public Nullable<int> ord { get; set; }
    }
}
