//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ainvh
    {
        public int docentry { get; set; }
        public string itemcode { get; set; }
        public string itemdesc { get; set; }
        public Nullable<System.DateTime> updt { get; set; }
        public string roomtemp { get; set; }
        public string remarks { get; set; }
        public string category { get; set; }
    }
}
