//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALABANG_008_SCSkeletal_20180705
    {
        public System.DateTime DocDate { get; set; }
        public string Description { get; set; }
        public string Typ { get; set; }
        public int Stat { get; set; }
        public string BranchCode { get; set; }
    }
}
