//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALULHdr
    {
        public string SecCode { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<byte> Stat { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string PostBy { get; set; }
        public Nullable<System.DateTime> RepostDate { get; set; }
        public string RepostBy { get; set; }
    }
}
