//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class amrd
    {
        public int docentry { get; set; }
        public string Docnum { get; set; }
        public string Docname { get; set; }
        public string Branch { get; set; }
        public string Encodedby { get; set; }
        public Nullable<System.DateTime> Encodeddate { get; set; }
        public string whscode { get; set; }
    }
}
