//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANTIBIOTIC_TBl
    {
        public int DOCENTRY { get; set; }
        public string AB_CODE { get; set; }
        public string AB_NAME { get; set; }
        public string AB_GROUP { get; set; }
        public string AB_OXOID { get; set; }
        public string AB_SEQNO { get; set; }
        public string AB_SHORT_NAME { get; set; }
        public Nullable<System.DateTime> DATE_OF_EFFECTIVITY { get; set; }
    }
}
