//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantReqLog
    {
        public string AppCode { get; set; }
        public string Resume { get; set; }
        public string Transcript { get; set; }
        public string BoardCert { get; set; }
        public string BoardRating { get; set; }
        public byte[] IdPic { get; set; }
        public string Diploma { get; set; }
        public string PRCId { get; set; }
        public string LogUser { get; set; }
        public string LogIP { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
