//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppOtherQ
    {
        public int AppCode { get; set; }
        public string Q1 { get; set; }
        public string Q2 { get; set; }
        public string Q3_1 { get; set; }
        public string Q3_2 { get; set; }
        public string Q3_3 { get; set; }
        public string Q4 { get; set; }
        public string Q5 { get; set; }
        public string Q6_1 { get; set; }
        public string Q6_2 { get; set; }
    }
}
