//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_mas_rec
    {
        public int docentry { get; set; }
        public string docnum { get; set; }
        public string Doctype { get; set; }
        public string Docname { get; set; }
        public string Initiator { get; set; }
        public string empid { get; set; }
        public string Branch { get; set; }
        public string whscode { get; set; }
        public string Users { get; set; }
        public string Rev { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Retention { get; set; }
        public string Disposal { get; set; }
        public Nullable<System.DateTime> Encodeddate { get; set; }
        public string Encodedby { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public string Updateby { get; set; }
    }
}
