//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCFile
    {
        public int DocEntry { get; set; }
        public Nullable<int> DepID { get; set; }
        public string WhsCode { get; set; }
        public string FName { get; set; }
        public string FPath { get; set; }
        public Nullable<int> Stat { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string DelBy { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public string IPAdd { get; set; }
    }
}
