//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCGenID
    {
        public int GenID { get; set; }
        public string CashierID { get; set; }
        public string WhsCode { get; set; }
        public Nullable<decimal> CashAmt { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<int> Stat { get; set; }
        public string UserID { get; set; }
        public Nullable<int> CutOff { get; set; }
        public Nullable<int> DepID { get; set; }
    }
}
