//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIGenLog
    {
        public int GenID { get; set; }
        public string EmpCode { get; set; }
        public int Yr { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Additional { get; set; }
        public Nullable<decimal> NewBalance { get; set; }
        public Nullable<decimal> OrigBal { get; set; }
        public int DocEntry { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IPAdd { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public string AccState { get; set; }
        public string LogType { get; set; }
    }
}
