//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blueprint
    {
        public string BPCode { get; set; }
        public int ProgId { get; set; }
        public int BPId { get; set; }
        public Nullable<int> DeptCode { get; set; }
        public Nullable<int> SecCode { get; set; }
        public string DevCode { get; set; }
        public string SupCode { get; set; }
        public string BPName { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Objective { get; set; }
        public string Users { get; set; }
        public string PMClient { get; set; }
        public string PMDev { get; set; }
        public string Reports { get; set; }
        public string TblsFlds { get; set; }
        public string FrmsObjs { get; set; }
        public string Process { get; set; }
        public Nullable<int> Stat { get; set; }
        public Nullable<int> IsNew { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<System.DateTime> DevDate { get; set; }
        public Nullable<System.DateTime> UATDate { get; set; }
        public string UATBy { get; set; }
        public Nullable<System.DateTime> QADate { get; set; }
        public string QABy { get; set; }
    }
}
