//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public string Code { get; set; }
        public string WhsName { get; set; }
        public string IpAdd { get; set; }
        public string Suffix { get; set; }
        public string POSPath { get; set; }
    }
}
