//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BscPriceLvl_Master
    {
        public int DocEntry { get; set; }
        public string Company { get; set; }
        public string Plvl1 { get; set; }
        public string Plvl2 { get; set; }
        public string Plvl3 { get; set; }
        public string MotherWhs { get; set; }
    }
}
