//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCLH
    {
        public int Doentry { get; set; }
        public string DocType { get; set; }
        public string RefNo { get; set; }
        public string DocName { get; set; }
        public string Inititator { get; set; }
        public string OwnerSec { get; set; }
        public string UserSec { get; set; }
        public string Revision { get; set; }
        public Nullable<System.DateTime> EffDate { get; set; }
        public string Encodedby { get; set; }
        public Nullable<System.DateTime> Encodeddate { get; set; }
        public string Obsolete { get; set; }
        public string AttachName { get; set; }
        public string HPpdf { get; set; }
        public string HPPluspdf { get; set; }
        public string ADVpdf { get; set; }
        public string DMpdf { get; set; }
        public string LPpdf { get; set; }
        public string EApdf { get; set; }
        public string ANGpdf { get; set; }
    }
}
