//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLog
    {
        public string ProgName { get; set; }
        public string ProgVer { get; set; }
        public System.DateTime ProgDate { get; set; }
        public string ProgLog { get; set; }
        public bool ProgStat { get; set; }
    }
}
