//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLOGS1
    {
        public Nullable<int> docentry { get; set; }
        public System.DateTime docdate { get; set; }
        public string destination { get; set; }
        public string stat { get; set; }
        public Nullable<int> duration { get; set; }
        public string local { get; set; }
    }
}
