//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMTTBL
    {
        public int DOCENTRY { get; set; }
        public string FE_CODE { get; set; }
        public string FE_DESC { get; set; }
        public string FE_STRING { get; set; }
        public Nullable<System.DateTime> DATE_DONE { get; set; }
        public Nullable<bool> STATUS_CREATED { get; set; }
    }
}
