//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColBrDeposit1
    {
        public int DocEntry { get; set; }
        public int LineID { get; set; }
        public Nullable<int> RefDocEntry { get; set; }
        public Nullable<int> RefLineID { get; set; }
        public string CheckNo { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string LabNo { get; set; }
        public string WhsCode { get; set; }
        public string LnRemarks { get; set; }
        public Nullable<int> CTDoc { get; set; }
        public Nullable<int> CTLine { get; set; }
    }
}
