//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColUpd_FORMULA_EXPR
    {
        public string DocEntry { get; set; }
        public string FE_CODe { get; set; }
        public string FE_DESC { get; set; }
        public string FE_STRING { get; set; }
        public string IP { get; set; }
        public string CreatedBy { get; set; }
        public string DateCreated { get; set; }
    }
}
