//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColUpd_test_item
    {
        public int Docentry { get; set; }
        public string testcode { get; set; }
        public string Col { get; set; }
        public string Val { get; set; }
        public Nullable<System.DateTime> Created_on { get; set; }
        public string Created_by { get; set; }
        public string Ip { get; set; }
        public string branch { get; set; }
    }
}
