//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColUpd_TESTPROFILE
    {
        public int DOCENTRY { get; set; }
        public string TP_CODE { get; set; }
        public string TP_TI_CODE { get; set; }
        public string TP_DISP_SEQ { get; set; }
        public string TP_HIDE_PRINT { get; set; }
        public string TP_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> TP_UPDATE_ON { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public string IP { get; set; }
    }
}
