//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColUpd_CMT_TBL
    {
        public int Docentry { get; set; }
        public string cmt_type { get; set; }
        public string cmt_code { get; set; }
        public string cmt_desc { get; set; }
        public Nullable<System.DateTime> Datecrated { get; set; }
        public string CreatedBy { get; set; }
        public string IP { get; set; }
    }
}
