//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int ID { get; set; }
        public string CONNECTION_NAME { get; set; }
        public string CONNECTION_TYPE { get; set; }
        public string DATA_SOURCE { get; set; }
        public string INITIAL_CATALOG { get; set; }
        public string UID { get; set; }
        public string PWD { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    }
}
