//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class daudittask
    {
        public int docentry { get; set; }
        public string task { get; set; }
        public string tdesc { get; set; }
        public string ttype { get; set; }
        public string tby { get; set; }
        public string Stat { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<System.DateTime> fdate { get; set; }
        public string approveby { get; set; }
        public Nullable<System.DateTime> adate { get; set; }
        public string rq { get; set; }
        public Nullable<System.DateTime> rq_date { get; set; }
        public string rq_rem { get; set; }
        public string dreason { get; set; }
    }
}
