//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocLog
    {
        public int DocEntry { get; set; }
        public System.DateTime DocDate { get; set; }
        public string RecType { get; set; }
        public string Query { get; set; }
        public string DocEncoder { get; set; }
        public string ModifyEmp { get; set; }
    }
}
