//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOHSign
    {
        public string EmpCode { get; set; }
        public string CTC { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public string PlaceIssued { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string Validity { get; set; }
    }
}
