//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRProg
    {
        public string Srvr { get; set; }
        public string Dbase { get; set; }
        public string Tbl { get; set; }
        public string Cond { get; set; }
        public string Prog { get; set; }
        public string ItmGrp { get; set; }
        public string DrCode { get; set; }
        public string DrName { get; set; }
    }
}
