//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTRLog
    {
        public int LogId { get; set; }
        public string WhsCode { get; set; }
        public string SheetName { get; set; }
        public Nullable<System.DateTime> DateImport { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DTRStat { get; set; }
        public Nullable<int> DTREntry { get; set; }
    }
}
