//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAnncmnt
    {
        public int DocEntry { get; set; }
        public System.DateTime DocDate { get; set; }
        public string Mode { get; set; }
        public string Subject { get; set; }
        public string Venue { get; set; }
        public string Event { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<System.TimeSpan> TimeFrom { get; set; }
        public Nullable<System.TimeSpan> TimeTo { get; set; }
        public string TrgtAttndees { get; set; }
        public Nullable<decimal> MaxNo { get; set; }
        public string Speaker { get; set; }
        public string Objective { get; set; }
        public string Contract { get; set; }
        public Nullable<decimal> NoYrs { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Companion { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<System.DateTime> DateSubmission { get; set; }
    }
}
