//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empbio_tk2
    {
        public string EmpCode { get; set; }
        public byte[] FP0 { get; set; }
        public byte[] FP1 { get; set; }
        public byte[] FP2 { get; set; }
        public byte[] FP3 { get; set; }
        public byte[] FP4 { get; set; }
        public byte[] FP5 { get; set; }
        public byte[] FP6 { get; set; }
        public byte[] FP7 { get; set; }
        public byte[] FP8 { get; set; }
        public byte[] FP9 { get; set; }
    }
}
