//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpCharRef
    {
        public int DocEntry { get; set; }
        public string EmpCode { get; set; }
        public string CName { get; set; }
        public string CNo { get; set; }
        public Nullable<int> CYear { get; set; }
        public string Occupation { get; set; }
    }
}
