//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emplastpay
    {
        public int id { get; set; }
        public string Empcode { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string Checkno { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DateClaimed { get; set; }
        public Nullable<int> Docid { get; set; }
    }
}
