//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLeaveHistBK
    {
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string EmpCode { get; set; }
        public string LeaveType { get; set; }
        public Nullable<decimal> LeaveUsed { get; set; }
        public Nullable<System.DateTime> DateLeave { get; set; }
        public string Remarks { get; set; }
        public string HRRemarks { get; set; }
        public Nullable<int> Stat { get; set; }
    }
}
