//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPPrc
    {
        public string EmpCode { get; set; }
        public string PRCId { get; set; }
        public string PRCDesc { get; set; }
        public Nullable<System.DateTime> PRCReg { get; set; }
        public Nullable<System.DateTime> PRCExp { get; set; }
        public Nullable<System.DateTime> PRCRenew { get; set; }
        public string Ratings { get; set; }
    }
}
