//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpResignTen
    {
        public string EmpCode { get; set; }
        public string DateHired { get; set; }
        public System.DateTime DateResigned { get; set; }
        public System.DateTime DateFiled { get; set; }
    }
}
