//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpSrvItem
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public decimal ItemPrice { get; set; }
        public string Benefit { get; set; }
        public string SD { get; set; }
        public string Cash { get; set; }
        public int Limit { get; set; }
        public string Size { get; set; }
        public string DeducCode { get; set; }
        public Nullable<System.DateTime> CutOff { get; set; }
    }
}
