//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTrainDtl
    {
        public int DocEntry { get; set; }
        public string EmpCode { get; set; }
        public string NickName { get; set; }
        public string MgmtCode { get; set; }
        public Nullable<System.DateTime> MgmtStatDate { get; set; }
        public string HRCode { get; set; }
        public Nullable<System.DateTime> HRStatDate { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string isPresent { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
