//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncAllow
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Branch { get; set; }
        public string Position { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Total_Encoded { get; set; }
        public Nullable<int> Excess_Encoded { get; set; }
        public decimal Allowance { get; set; }
        public Nullable<decimal> Excess_Allowance { get; set; }
        public Nullable<decimal> Encoded_Amount { get; set; }
        public Nullable<decimal> ALUL_Minutes { get; set; }
        public Nullable<decimal> ALUL_Rate { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
    }
}
