//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fdlistrose
    {
        public int DelID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string LabNo { get; set; }
        public string EncBy { get; set; }
        public string Patient { get; set; }
        public string RefNo { get; set; }
        public string Reason { get; set; }
        public string RelabNo { get; set; }
        public string WhsCode { get; set; }
        public string Stat { get; set; }
        public Nullable<System.DateTime> TagDate { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public Nullable<int> IfDel { get; set; }
        public string source { get; set; }
        public string DelBy { get; set; }
        public string PType { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
