//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDReq
    {
        public Nullable<int> Docentry { get; set; }
        public Nullable<System.DateTime> Docdate { get; set; }
        public string LabNo { get; set; }
        public string WhsCode { get; set; }
        public string DecRemarks { get; set; }
    }
}
