//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenTrig
    {
        public string Program { get; set; }
        public string Host { get; set; }
        public string IP { get; set; }
        public System.DateTime DocDate { get; set; }
        public string Query { get; set; }
    }
}
