//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HepaPType
    {
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string EmpID { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string PType { get; set; }
        public string DeducDoc { get; set; }
        public string DeDucTag { get; set; }
        public Nullable<int> OIGE { get; set; }
    }
}
