//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HKAuditCompile
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Branch { get; set; }
        public string BranchDept { get; set; }
        public string WhsCode { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string PreparedID { get; set; }
        public string PreparedBy { get; set; }
        public string Findings { get; set; }
        public string Recommendations { get; set; }
        public string Location { get; set; }
        public string Department { get; set; }
        public string ActionTaken { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string ImgBefore { get; set; }
        public string ImgAfter { get; set; }
        public string Stat { get; set; }
        public string StatPerFind { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string ClosedID { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> SubBranchDate { get; set; }
        public string SubBranchID { get; set; }
        public string SubBranchBy { get; set; }
        public string VerifiedID { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public string BrType { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string RefNo { get; set; }
        public string TypeFinding { get; set; }
        public string Delstat { get; set; }
        public string Delby { get; set; }
        public Nullable<System.DateTime> Deldate { get; set; }
    }
}
