//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HKAudit
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Branch { get; set; }
        public string BranchDept { get; set; }
        public string WhsCode { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string PreparedID { get; set; }
        public string PreparedBy { get; set; }
        public string Findings { get; set; }
        public string Recommendations { get; set; }
        public string Location { get; set; }
        public string Department { get; set; }
        public string ActionTaken { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string ImgBefore { get; set; }
        public string ImgAfter { get; set; }
        public string Stat { get; set; }
        public string StatPerFind { get; set; }
        public string ClosedID { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string AddByID { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> SubBranchDate { get; set; }
        public string SubBranchID { get; set; }
        public string SubBranchBy { get; set; }
        public Nullable<System.DateTime> BrChkDate { get; set; }
        public string BrChkID { get; set; }
        public string BrChkBy { get; set; }
        public string VerifiedID { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public string VerSubID { get; set; }
        public string VerSubBy { get; set; }
        public Nullable<System.DateTime> VerSubDate { get; set; }
        public Nullable<int> Observation { get; set; }
        public Nullable<int> Closed { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<bool> TransRpt { get; set; }
        public Nullable<bool> tmpE { get; set; }
        public string BrType { get; set; }
        public Nullable<System.DateTime> REVerSubDate { get; set; }
        public string REVerSubID { get; set; }
        public string REVerSubBy { get; set; }
        public string RefNo { get; set; }
        public string TypeFinding { get; set; }
        public string FCNRID { get; set; }
        public string FCNRBY { get; set; }
        public Nullable<System.DateTime> FCNRDate { get; set; }
        public string FCFVID { get; set; }
        public string FCFVBY { get; set; }
        public Nullable<System.DateTime> FCFVDate { get; set; }
        public string delstat { get; set; }
        public string delby { get; set; }
        public string delid { get; set; }
        public Nullable<System.DateTime> deldt { get; set; }
    }
}
