//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HPD1SrcCode
    {
        public string SrcCode { get; set; }
        public string SrcName { get; set; }
        public string SrcCont { get; set; }
        public string SrcAdd { get; set; }
    }
}
