//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDEmpReq
    {
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string EmpCode { get; set; }
        public string Reason { get; set; }
        public string EmpEConName { get; set; }
        public string EmpEConRel { get; set; }
        public string EmpEConNum { get; set; }
        public string EmpEConAdd { get; set; }
        public string Affdvt { get; set; }
        public string ReqStat { get; set; }
        public string AppBy { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public string Remarks { get; set; }
        public string Sign { get; set; }
        public string sig { get; set; }
    }
}
