//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDTK_20180531
    {
        public string TKIDNo { get; set; }
        public string Empcode { get; set; }
        public string WhsCode { get; set; }
        public string SheetName { get; set; }
    }
}
