//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgPCFDtl
    {
        public int BaseEntry { get; set; }
        public int LineNum { get; set; }
        public string WhsCode { get; set; }
        public string TrxNo { get; set; }
        public Nullable<System.DateTime> TrxDate { get; set; }
        public string PxName { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> PFAmt { get; set; }
    }
}
