//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgPCFHdr
    {
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public int BaseEntry { get; set; }
        public string RlvrName { get; set; }
        public string Typ { get; set; }
        public string WhsCode { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public Nullable<decimal> TotAmt { get; set; }
        public string Fund { get; set; }
        public Nullable<int> PCFEntry { get; set; }
        public string PostBy { get; set; }
        public string ModBy { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public string GenID { get; set; }
        public Nullable<System.DateTime> GenDate { get; set; }
        public string GenBy { get; set; }
        public string IPAdd { get; set; }
        public Nullable<int> OPEntry { get; set; }
        public Nullable<System.DateTime> OPDate { get; set; }
    }
}
