//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDTRTag
    {
        public string EmpCode { get; set; }
        public System.DateTime DocDate { get; set; }
        public string TI { get; set; }
        public string LO { get; set; }
        public string LI { get; set; }
        public string TO { get; set; }
        public string BO { get; set; }
        public string BI { get; set; }
        public string BO1 { get; set; }
        public string BI1 { get; set; }
        public string Stat { get; set; }
        public string TagBy { get; set; }
        public Nullable<System.DateTime> TagDate { get; set; }
    }
}
