//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQA_hdr
    {
        public string RefNo { get; set; }
        public string Purpose { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string LeadAud { get; set; }
        public string Auditor { get; set; }
        public string ReviewBy { get; set; }
        public string NotedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Branch { get; set; }
        public string PrepBy { get; set; }
        public string PrepID { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string Stat { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public string ValidBy { get; set; }
        public string ValidID { get; set; }
        public Nullable<System.DateTime> ComDate { get; set; }
        public Nullable<System.DateTime> SubBranch { get; set; }
        public Nullable<System.DateTime> SubChk { get; set; }
        public string Dept { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<System.DateTime> REVerSubDate { get; set; }
        public string REVerSubID { get; set; }
        public string REVerSubBy { get; set; }
        public Nullable<System.DateTime> VerSubDate { get; set; }
        public string VerSubID { get; set; }
        public string VerSubBy { get; set; }
        public Nullable<bool> FV { get; set; }
        public string FCNRID { get; set; }
        public string FCNRBY { get; set; }
        public Nullable<System.DateTime> FCNRDate { get; set; }
        public string FCFVID { get; set; }
        public string FCFVBY { get; set; }
        public Nullable<System.DateTime> FCFVDate { get; set; }
        public string whscode { get; set; }
        public string delstat { get; set; }
        public Nullable<System.DateTime> Deldt { get; set; }
        public string Delby { get; set; }
    }
}
