//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_ALUL
    {
        public int Empcode { get; set; }
        public string EmpName { get; set; }
        public string Dept { get; set; }
        public string AccDept { get; set; }
    }
}
