//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDT1
    {
        public int TransID { get; set; }
        public string line_ID { get; set; }
        public string Segment0 { get; set; }
        public string Segment1 { get; set; }
        public string SEgment2 { get; set; }
        public string AcctName { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<int> BaseRef { get; set; }
        public string Remarks { get; set; }
        public string Transtype { get; set; }
        public string FormatCode { get; set; }
        public Nullable<System.DateTime> refdate { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Ref3 { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public string ShortName { get; set; }
    }
}
