//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JEUnif
    {
        public int Docentry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<int> Transid { get; set; }
        public string Empid { get; set; }
        public Nullable<decimal> Doctotal { get; set; }
    }
}
