//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDescReq
    {
        public int Docentry { get; set; }
        public string EmpCode { get; set; }
        public string ReqType { get; set; }
        public string reqFrom { get; set; }
        public string reqTo { get; set; }
        public string UT { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public string ReqBy { get; set; }
        public string ReqStat { get; set; }
        public string HrCode { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
    }
}
