//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMReadingTable
    {
        public string DocEntry { get; set; }
        public string EmpCode { get; set; }
        public System.DateTime DocDate { get; set; }
        public bool Defective { get; set; }
        public decimal FirstKM { get; set; }
        public decimal LastKM { get; set; }
        public decimal Allowance { get; set; }
        public string Remarks { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ReqStat { get; set; }
        public string ReqStatBy { get; set; }
        public Nullable<System.DateTime> ReqStatDate { get; set; }
        public string ReqStatRemarks { get; set; }
    }
}
