//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIDtl
    {
        public string U_LabNo { get; set; }
        public string U_ItemCode { get; set; }
        public Nullable<System.DateTime> U_TransDate { get; set; }
        public string U_Source { get; set; }
        public Nullable<decimal> U_UnitPrice { get; set; }
        public Nullable<int> U_Qty { get; set; }
        public Nullable<decimal> U_DiscAmt { get; set; }
        public string U_PriceLvl { get; set; }
        public string U_PackageNo { get; set; }
        public string U_RefNumber { get; set; }
        public string WhsCode { get; set; }
        public string BCan { get; set; }
        public Nullable<decimal> U_AdjAmt { get; set; }
    }
}
