//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIHdr
    {
        public int U_LabNo { get; set; }
        public Nullable<System.DateTime> U_TransDate { get; set; }
        public string U_Patient { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string WhsCode { get; set; }
        public string Encoder { get; set; }
        public string CardCode { get; set; }
        public string U_DoctorCode { get; set; }
        public string U_PatientTyp { get; set; }
        public string U_PaymentTyp { get; set; }
        public string U_Status { get; set; }
        public string PN { get; set; }
        public string Remarks { get; set; }
        public string PID { get; set; }
        public string IsZero { get; set; }
        public string Age { get; set; }
        public string ClinInfo { get; set; }
    }
}
