//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local_BR
    {
        public int COunter { get; set; }
        public string branchname { get; set; }
        public string landline { get; set; }
        public string fax { get; set; }
        public string mobile { get; set; }
        public string branch_oic { get; set; }
    }
}
