//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERDet
    {
        public Nullable<int> DocEntry { get; set; }
        public string EmpCode { get; set; }
        public System.DateTime DocDate { get; set; }
        public string Particular { get; set; }
        public string Territory { get; set; }
        public Nullable<decimal> TA { get; set; }
        public Nullable<decimal> VR { get; set; }
        public Nullable<decimal> PTF { get; set; }
        public Nullable<decimal> MEE { get; set; }
        public Nullable<decimal> RF { get; set; }
        public Nullable<decimal> CR { get; set; }
        public Nullable<decimal> OE { get; set; }
        public string Remarks { get; set; }
        public string DSMStat { get; set; }
        public string DSMEmpCode { get; set; }
        public Nullable<System.DateTime> DSMStatDate { get; set; }
        public string SMStat { get; set; }
        public string SMEmpCode { get; set; }
        public Nullable<System.DateTime> SMStatDate { get; set; }
        public string HRStat { get; set; }
        public string HREmpCode { get; set; }
        public Nullable<System.DateTime> HRStatDate { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public string ReqStat { get; set; }
        public string ReqRemarks { get; set; }
    }
}
