//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerDetComment
    {
        public string Empid { get; set; }
        public string Pr { get; set; }
        public int Yr { get; set; }
        public string NameDate { get; set; }
        public System.DateTime OrigDate { get; set; }
        public string VehicleCom { get; set; }
        public string MarketCom { get; set; }
        public string WorkingCom { get; set; }
        public string OthersCom { get; set; }
        public string ExpenseCom { get; set; }
    }
}
