//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERHdr
    {
        public string DocEntry { get; set; }
        public string EmpCode { get; set; }
        public string HomeBase { get; set; }
        public string District { get; set; }
        public Nullable<decimal> MealAllow { get; set; }
        public Nullable<decimal> TransPo { get; set; }
        public Nullable<decimal> Parking { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public Nullable<decimal> Internet { get; set; }
        public string Stat { get; set; }
        public string PayEntry { get; set; }
    }
}
