//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerReceipt
    {
        public int Docentry { get; set; }
        public string Empid { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> ReceiptNo { get; set; }
    }
}
