//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERSchedDet
    {
        public int Docentry { get; set; }
        public int LineNum { get; set; }
        public string Empcode { get; set; }
        public Nullable<decimal> MA { get; set; }
    }
}
