//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERSched
    {
        public System.DateTime DocDate { get; set; }
        public string Dsc { get; set; }
        public string MealAllow { get; set; }
        public string TrnspoAllow { get; set; }
        public string TrnspoGO { get; set; }
        public string VehicleRep { get; set; }
        public string AdminExp { get; set; }
        public string MrketEveOthers { get; set; }
        public string MrketEveChrge { get; set; }
        public string PhoneAllow { get; set; }
        public string InternetAllow { get; set; }
        public string Working { get; set; }
        public string Others { get; set; }
        public int Docentry { get; set; }
        public string ReqBy { get; set; }
    }
}
