//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFTTransLog
    {
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> docdate { get; set; }
        public string FName { get; set; }
        public string DestPath { get; set; }
    }
}
