//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiDTR
    {
        public int DocEntry { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public string Stat { get; set; }
        public Nullable<decimal> Working { get; set; }
        public Nullable<decimal> Late { get; set; }
        public Nullable<decimal> OT { get; set; }
        public Nullable<decimal> ND { get; set; }
        public Nullable<decimal> NDOT { get; set; }
        public Nullable<decimal> Food { get; set; }
        public string EmpType { get; set; }
    }
}
