//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiListLog
    {
        public int DocEntry { get; set; }
        public string MissionID { get; set; }
        public System.DateTime DocDate { get; set; }
        public string MiDesc { get; set; }
        public string MiArea { get; set; }
        public System.TimeSpan STime { get; set; }
        public System.TimeSpan ETime { get; set; }
        public System.TimeSpan CTime { get; set; }
        public System.TimeSpan ATime { get; set; }
        public string MiStatus { get; set; }
        public string LogId { get; set; }
        public string LogIP { get; set; }
        public System.DateTime LogDate { get; set; }
    }
}
