//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIPatListdet
    {
        public string MissionID { get; set; }
        public string ClientName { get; set; }
        public string LabNo { get; set; }
        public string TestID { get; set; }
        public string PatientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte Gender { get; set; }
        public System.DateTime BirthDate { get; set; }
        public byte Age { get; set; }
        public byte MarkerType { get; set; }
        public bool FormReturnedFlag { get; set; }
        public System.DateTime MissionDateFrom { get; set; }
        public System.DateTime MissionDateTo { get; set; }
        public Nullable<int> DocNum { get; set; }
        public int DocEntry { get; set; }
    }
}
