//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MocK_Elec
    {
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string President { get; set; }
        public string VicePres { get; set; }
        public Nullable<int> PCode { get; set; }
        public Nullable<int> VCode { get; set; }
    }
}
