//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotUpdateCol_Backup_09_09_2017
    {
        public int docentry { get; set; }
        public string Branchname { get; set; }
        public string IPAdd { get; set; }
        public string TestCode { get; set; }
        public string ColName { get; set; }
    }
}
