//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODATC
    {
        public string Dcode { get; set; }
        public string DName { get; set; }
        public string ATCCode { get; set; }
        public Nullable<decimal> ATCRate { get; set; }
        public string isActive { get; set; }
    }
}
