//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEMPTEST
    {
        public string EmpCode { get; set; }
        public string PID { get; set; }
        public string EmpName { get; set; }
        public string EmpAddress { get; set; }
        public string EmpSex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public string WhsCode { get; set; }
        public string Dept { get; set; }
        public string SSSNo { get; set; }
        public string TINNo { get; set; }
        public string GSISNo { get; set; }
        public string PAGIBIGNo { get; set; }
        public string PHILHEALTHNo { get; set; }
        public string Encoder { get; set; }
        public Nullable<System.DateTime> DateEncoded { get; set; }
        public Nullable<decimal> CurrBal { get; set; }
        public Nullable<decimal> OrigBal { get; set; }
        public Nullable<System.DateTime> CurrDate { get; set; }
        public string Stat { get; set; }
        public string BasicPay { get; set; }
        public string OT { get; set; }
        public string ND { get; set; }
        public Nullable<int> Premium { get; set; }
        public string P_Stat { get; set; }
        public string Position { get; set; }
        public string PicLoc { get; set; }
        public Nullable<System.DateTime> DateResigned { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string Active { get; set; }
        public string UpdErr { get; set; }
        public string EmpType { get; set; }
        public string IPAddress { get; set; }
        public string AcctNo { get; set; }
        public string ResignRemarks { get; set; }
        public string EmpType1 { get; set; }
        public string CivilStatus { get; set; }
        public Nullable<System.DateTime> DateFiled { get; set; }
        public Nullable<bool> ResignLetter { get; set; }
        public string OnCall { get; set; }
        public string ResignReason { get; set; }
        public string EmailAdd { get; set; }
        public string SSSIDTag { get; set; }
        public string PAGIBIGIDTag { get; set; }
        public string PHILHLTHIDTag { get; set; }
        public string EmpAdd { get; set; }
    }
}
