//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCheck
    {
        public int OPEntry { get; set; }
        public string CheckNum { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
    }
}
