//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ord_trx_det
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public string BranchName { get; set; }
        public string IpAddress { get; set; }
        public Nullable<bool> Stat { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateDone { get; set; }
        public string Remarks { get; set; }
    }
}
