//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ord_trx
    {
        public int DocEntry { get; set; }
        public string TestCode { get; set; }
        public string TestDesc { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Created_By_ID { get; set; }
        public string Created_By_Name { get; set; }
        public string Remarks { get; set; }
    }
}
