//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANISM_TBL
    {
        public int DOCENTRY { get; set; }
        public string OG_CODE { get; set; }
        public string OG_NAME { get; set; }
        public string OG_GROUP { get; set; }
        public string OG_SHORT_NAME { get; set; }
        public string OG_ALERT { get; set; }
        public string OG_TEST_GRP { get; set; }
        public Nullable<System.DateTime> DATE_DONE { get; set; }
        public Nullable<bool> STATUS_CREATED { get; set; }
    }
}
