//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTEmpReqTEST
    {
        public string DocEntry { get; set; }
        public string EmpCode { get; set; }
        public System.DateTime DocDate { get; set; }
        public string SchedTime { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public decimal OTTI { get; set; }
        public decimal OTTO { get; set; }
        public decimal ROT { get; set; }
        public decimal NDF8 { get; set; }
        public decimal NDX8 { get; set; }
        public decimal OT_RDF8 { get; set; }
        public decimal OT_RHF8 { get; set; }
        public decimal OT_SHF8_M { get; set; }
        public decimal OT_RDX8 { get; set; }
        public decimal OT_SHX8 { get; set; }
        public decimal OT_RHX8 { get; set; }
        public decimal OT_SHRDF8 { get; set; }
        public decimal OT_RHRDF8 { get; set; }
        public decimal OT_SHRDX8 { get; set; }
        public decimal OT_RHRDX8 { get; set; }
        public decimal ND_RDF8 { get; set; }
        public decimal ND_RHF8 { get; set; }
        public decimal ND_SHF8 { get; set; }
        public decimal ND_SHF8_M { get; set; }
        public decimal ND_RDX8 { get; set; }
        public decimal ND_SHX8 { get; set; }
        public decimal ND_RHX8 { get; set; }
        public decimal ND_RHRDF8 { get; set; }
        public decimal ND_SHRDF8 { get; set; }
        public decimal ND_SHRDX8 { get; set; }
        public decimal ND_RHRDX8 { get; set; }
        public decimal OT_SHF8 { get; set; }
        public Nullable<System.DateTime> DateRequest { get; set; }
        public string SupStat { get; set; }
        public Nullable<System.DateTime> SupStatDate { get; set; }
        public string SupEmpCode { get; set; }
        public string MgmtStat { get; set; }
        public Nullable<System.DateTime> MgmtStatDate { get; set; }
        public string MgmtEmpCode { get; set; }
        public Nullable<System.DateTime> DateTagged { get; set; }
        public string TaggedBy { get; set; }
        public Nullable<System.DateTime> DateCancelled { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public string PaidBy { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public string ReqStat { get; set; }
    }
}
