//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTTag
    {
        public string DocEntry { get; set; }
        public int LinNum { get; set; }
        public string EmpId { get; set; }
        public string EmpName { get; set; }
        public System.DateTime Docdate { get; set; }
        public Nullable<decimal> OTTO { get; set; }
        public Nullable<decimal> OTTI { get; set; }
        public Nullable<int> ND { get; set; }
        public Nullable<decimal> NDOT { get; set; }
        public Nullable<decimal> RDOT { get; set; }
        public Nullable<decimal> TotOT { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<System.TimeSpan> TimeAprroved { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<System.TimeSpan> TimePaid { get; set; }
        public string ApprovedBy { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<System.DateTime> DateCancelled { get; set; }
        public string OTStat { get; set; }
        public string Hold { get; set; }
        public int DocID { get; set; }
    }
}
