//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class owh
    {
        public string BID { get; set; }
        public string Code { get; set; }
        public string WhsName { get; set; }
        public string Blk { get; set; }
        public string IPadd { get; set; }
        public string stat { get; set; }
    }
}
