//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCF
    {
        public int OPEntry { get; set; }
        public int SAPEntry { get; set; }
        public string Descrip { get; set; }
        public int DocEntry { get; set; }
        public string WhsCode { get; set; }
        public string ATCCode { get; set; }
        public Nullable<decimal> ATCRate { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
    }
}
