//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCf2ndInCmd
    {
        public string Empid { get; set; }
        public string EmpName { get; set; }
        public string Whscode { get; set; }
        public string CustodianAcct { get; set; }
        public Nullable<byte> isActive { get; set; }
        public Nullable<System.DateTime> DeActDate { get; set; }
        public Nullable<System.DateTime> s { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public string WithExp { get; set; }
        public string AccLvl { get; set; }
    }
}
