//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCfcustod
    {
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public string WhsCode { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> Docentry { get; set; }
        public Nullable<System.DateTime> RDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> PrevBal { get; set; }
        public Nullable<int> ReplenishDay { get; set; }
        public string ReplenishType { get; set; }
        public Nullable<System.DateTime> LastReplenish { get; set; }
        public string Activate { get; set; }
        public string UserAssign { get; set; }
        public string AutoApp { get; set; }
        public Nullable<System.DateTime> NextRepdt { get; set; }
        public string PFAssign { get; set; }
    }
}
