//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCFCalendar
    {
        public int Docentry { get; set; }
        public string Whscode { get; set; }
        public int RepID { get; set; }
        public int SDy { get; set; }
        public Nullable<int> DyofTran { get; set; }
        public Nullable<int> RepDy { get; set; }
        public string CustodID { get; set; }
        public Nullable<int> MonthlySdy { get; set; }
    }
}
