//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCFErrDelete
    {
        public int ID { get; set; }
        public Nullable<int> ErrCount { get; set; }
        public Nullable<int> ErrEntry { get; set; }
        public Nullable<int> BranchEntry { get; set; }
        public string Whscode { get; set; }
        public Nullable<int> DelMonteEntry { get; set; }
        public string CustodianID { get; set; }
        public string CustodianName { get; set; }
        public string OthersRemarks { get; set; }
        public Nullable<System.DateTime> Trxdate { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Stat { get; set; }
        public Nullable<int> Linenum { get; set; }
        public Nullable<System.DateTime> ErrorDate { get; set; }
        public string Genby { get; set; }
        public string Deleteby { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    }
}
