//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pcfovpm
    {
        public int OPEntry { get; set; }
        public Nullable<System.DateTime> docdate { get; set; }
        public string WhsCode { get; set; }
        public string payto { get; set; }
        public string remarks { get; set; }
        public string BankName { get; set; }
        public Nullable<int> BankCode { get; set; }
        public string Vendors { get; set; }
        public string Stat { get; set; }
        public string WhsV { get; set; }
        public string Rtype { get; set; }
        public Nullable<int> SAPEntry { get; set; }
        public string custodian { get; set; }
        public string PostBy { get; set; }
        public Nullable<decimal> TotAmt { get; set; }
        public Nullable<System.DateTime> SalesInvDate { get; set; }
        public Nullable<System.DateTime> SalesInvDateReceive { get; set; }
        public string Checknum { get; set; }
        public string TransID { get; set; }
        public string SI { get; set; }
        public Nullable<int> Auth { get; set; }
        public string Release { get; set; }
        public Nullable<System.DateTime> vfrom { get; set; }
        public Nullable<System.DateTime> vTo { get; set; }
    }
}
