//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCFSum
    {
        public int RowNum { get; set; }
        public string Vendors { get; set; }
        public string Remarks { get; set; }
        public string Whscode { get; set; }
        public Nullable<int> Sapentry { get; set; }
        public System.DateTime From { get; set; }
        public System.DateTime To { get; set; }
        public Nullable<System.DateTime> Datecompleted { get; set; }
        public string replenishtype { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> RepDay { get; set; }
        public string NMRmks { get; set; }
    }
}
