//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pcfvpm4
    {
        public int Docnum { get; set; }
        public int LineID { get; set; }
        public string FormatCode { get; set; }
        public string AcctName { get; set; }
        public Nullable<decimal> SumApplied { get; set; }
        public string Descrip { get; set; }
    }
}
