//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCOProg
    {
        public int DocEntry { get; set; }
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public string Branch { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Program { get; set; }
        public string UserName { get; set; }
        public string PWord { get; set; }
    }
}
