//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCReq1
    {
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public string Program { get; set; }
        public string Branch { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
        public string Stat { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Username { get; set; }
        public string PWord { get; set; }
        public string ApprovedBy { get; set; }
        public string IPAdd { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string UpdateLine { get; set; }
        public string category { get; set; }
        public string DocEntry { get; set; }
        public string Req_Type { get; set; }
        public string EncodeBy { get; set; }
    }
}
