//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peer
    {
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string WhsCode { get; set; }
        public string Position { get; set; }
        public string Blk { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Pwd { get; set; }
        public string Dept { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public string Status { get; set; }
    }
}
