//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenaltyTag
    {
        public int PTCode { get; set; }
        public string EmpCode { get; set; }
        public System.DateTime DocDate { get; set; }
        public int PenalCode { get; set; }
        public System.DateTime DateTagged { get; set; }
        public string TaggedBy { get; set; }
        public string DeducTag { get; set; }
    }
}
