//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetronCust
    {
        public string EmpId { get; set; }
        public string FleetCrdStat { get; set; }
        public Nullable<System.DateTime> DtReturn { get; set; }
        public string DestinedBr { get; set; }
        public string FleetCrdNo { get; set; }
        public string CardType { get; set; }
        public Nullable<decimal> MnthFuelLimit { get; set; }
    }
}
