//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRCalendar
    {
        public string DocEntry { get; set; }
        public Nullable<System.DateTime> DocFrom { get; set; }
        public Nullable<System.DateTime> DocTo { get; set; }
        public Nullable<System.DateTime> DocEnd { get; set; }
        public Nullable<System.DateTime> SCD_CO { get; set; }
        public Nullable<System.DateTime> SCC_CO { get; set; }
        public Nullable<System.DateTime> OT_CO { get; set; }
        public Nullable<System.DateTime> EMP_CO { get; set; }
        public Nullable<System.DateTime> SUP_CO { get; set; }
        public Nullable<System.DateTime> MGMT_CO { get; set; }
    }
}
