//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcLog
    {
        public int DocEntry { get; set; }
        public string EmpCode { get; set; }
        public string Program { get; set; }
        public System.DateTime Datelog { get; set; }
        public int Active { get; set; }
        public string IPadd { get; set; }
        public string InUse { get; set; }
        public string Form { get; set; }
        public string Process { get; set; }
        public string ProcDesc { get; set; }
        public string Descr { get; set; }
        public string DocNum { get; set; }
    }
}
