//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgIssueShot
    {
        public Nullable<int> DocEntry { get; set; }
        public byte[] image_data { get; set; }
        public string image_name { get; set; }
    }
}
