//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgPrio2
    {
        public string EmpID { get; set; }
        public string Empname { get; set; }
        public System.DateTime dtDate { get; set; }
        public string Program { get; set; }
        public string Descr { get; set; }
        public string RequestedBy { get; set; }
        public string Stat { get; set; }
        public Nullable<int> blueprint { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    }
}
