//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class programs41
    {
        public string Program { get; set; }
        public string Area { get; set; }
        public string Module { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string InCharge { get; set; }
        public string SubMod { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string ProgDesc { get; set; }
        public string ProgVer { get; set; }
        public string CodePath { get; set; }
        public string ExePath { get; set; }
        public string LocalPath { get; set; }
        public Nullable<int> Active { get; set; }
        public string ProgType { get; set; }
        public Nullable<System.DateTime> BackupDate { get; set; }
        public string EmpCode { get; set; }
        public string TestVer { get; set; }
        public string origExepath { get; set; }
        public string ErrLog { get; set; }
        public string cloudexepath { get; set; }
    }
}
