//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PYMAddition
    {
        public int DocEntry { get; set; }
        public string Code { get; set; }
        public string Dscrpt { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string AcctCode { get; set; }
        public string AcctName { get; set; }
        public string DC { get; set; }
        public string AddType { get; set; }
    }
}
