//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PyMsgrPslip
    {
        public int DocEntry { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public Nullable<decimal> TotDay { get; set; }
        public Nullable<decimal> WLegDay { get; set; }
        public Nullable<decimal> UWLegDay { get; set; }
        public Nullable<decimal> WSpeDay { get; set; }
        public Nullable<decimal> USpeDay { get; set; }
        public Nullable<decimal> SunDay { get; set; }
        public Nullable<decimal> Late { get; set; }
        public Nullable<decimal> NDOT { get; set; }
        public Nullable<decimal> RegOT { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public Nullable<decimal> MO { get; set; }
        public Nullable<decimal> PhoneAllow { get; set; }
        public Nullable<decimal> GasAllow { get; set; }
        public Nullable<decimal> MotorOil { get; set; }
        public Nullable<decimal> PerfectAtt { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public Nullable<decimal> ECOLA { get; set; }
        public Nullable<decimal> Mission { get; set; }
        public Nullable<decimal> RegDay { get; set; }
        public Nullable<decimal> holiday { get; set; }
        public Nullable<decimal> BscPay { get; set; }
        public Nullable<decimal> OA { get; set; }
        public Nullable<int> UT { get; set; }
        public Nullable<decimal> Leave { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public string Remarks { get; set; }
    }
}
