//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PyParoll
    {
        public int DocEntry { get; set; }
        public Nullable<int> Mth { get; set; }
        public Nullable<int> Pd { get; set; }
        public Nullable<int> Yr { get; set; }
        public string EmpId { get; set; }
        public Nullable<decimal> BSPay { get; set; }
        public Nullable<decimal> BSECOLA { get; set; }
        public Nullable<decimal> BSOA { get; set; }
        public Nullable<decimal> BSTot { get; set; }
        public Nullable<decimal> SDay { get; set; }
        public Nullable<decimal> Late { get; set; }
        public Nullable<decimal> UnderTime { get; set; }
        public Nullable<int> PDay { get; set; }
        public Nullable<int> Absent { get; set; }
        public Nullable<decimal> GSalary { get; set; }
        public Nullable<decimal> OTAmt { get; set; }
        public Nullable<decimal> UT { get; set; }
        public Nullable<decimal> ECOLA { get; set; }
        public Nullable<decimal> OA { get; set; }
        public Nullable<decimal> SI { get; set; }
        public Nullable<decimal> MA { get; set; }
        public Nullable<decimal> MO { get; set; }
        public Nullable<decimal> AL { get; set; }
        public Nullable<decimal> AB { get; set; }
        public string ED1 { get; set; }
        public string ED2 { get; set; }
        public string ED3 { get; set; }
        public Nullable<decimal> EDAmt1 { get; set; }
        public Nullable<decimal> EDAmt2 { get; set; }
        public Nullable<decimal> EDAmt3 { get; set; }
        public Nullable<decimal> NetSlry { get; set; }
        public Nullable<decimal> TaxWhld { get; set; }
        public Nullable<decimal> SSPrem { get; set; }
        public Nullable<decimal> PHilHlth { get; set; }
        public Nullable<decimal> PagIbig { get; set; }
        public Nullable<decimal> TITO { get; set; }
        public Nullable<decimal> AR { get; set; }
        public Nullable<decimal> UN { get; set; }
        public Nullable<decimal> CT { get; set; }
        public string DD1 { get; set; }
        public string DD2 { get; set; }
        public string DD3 { get; set; }
        public Nullable<decimal> DDAmt1 { get; set; }
        public Nullable<decimal> DDAmt2 { get; set; }
        public Nullable<decimal> DDAmt3 { get; set; }
        public Nullable<decimal> TotDeduc { get; set; }
        public Nullable<decimal> NETPay { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DocDateFrom { get; set; }
        public Nullable<System.DateTime> DocDateTO { get; set; }
    }
}
