//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PYTK
    {
        public Nullable<int> DocEntry { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string EmpCode { get; set; }
        public string IDName { get; set; }
        public System.DateTime DocDate { get; set; }
        public string DocDay { get; set; }
        public string DocType { get; set; }
        public System.DateTime RegDate { get; set; }
        public System.DateTime RegTime { get; set; }
        public string SheetName { get; set; }
    }
}
