//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_STATUS
    {
        public int ID { get; set; }
        public string PARTICULARS { get; set; }
        public Nullable<System.DateTime> DEADLINE { get; set; }
        public string PIC { get; set; }
        public string STAT { get; set; }
    }
}
