//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetroDtl
    {
        public int DocEntry { get; set; }
        public string Coverage { get; set; }
        public string EmpCode { get; set; }
        public decimal WrkDay { get; set; }
        public decimal AbsDay { get; set; }
        public decimal TardyDay { get; set; }
        public decimal TotDay { get; set; }
        public decimal ROT { get; set; }
        public decimal ND { get; set; }
        public decimal RDOT { get; set; }
        public decimal NDOT { get; set; }
        public decimal LglDay { get; set; }
        public decimal SpcDay { get; set; }
        public string ClsRate { get; set; }
        public Nullable<bool> Stat { get; set; }
    }
}
