//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_PerWeek_Slsprsn
    {
        public int Yr { get; set; }
        public int Pd { get; set; }
        public int Slpcode { get; set; }
        public string Slpname { get; set; }
        public Nullable<decimal> Week1 { get; set; }
        public Nullable<decimal> Week2 { get; set; }
        public Nullable<decimal> Week3 { get; set; }
        public Nullable<decimal> Week4 { get; set; }
        public Nullable<decimal> Week5 { get; set; }
        public Nullable<decimal> Target { get; set; }
        public string District { get; set; }
        public string Whscode { get; set; }
    }
}
