//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int DocEntry { get; set; }
        public string LabNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public Nullable<decimal> AdjAmt { get; set; }
        public Nullable<int> Qty { get; set; }
        public string DCode { get; set; }
        public string CardCode { get; set; }
        public string WhsCode { get; set; }
        public string PMode { get; set; }
        public Nullable<int> Pd { get; set; }
        public Nullable<int> Yr { get; set; }
        public string Type { get; set; }
        public Nullable<int> Qtr { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<int> AnnualPd { get; set; }
        public string ActTyp { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public string SlpName { get; set; }
        public string CardName { get; set; }
        public string DName { get; set; }
        public string AccClin { get; set; }
        public Nullable<int> TransID { get; set; }
        public string Segment_0 { get; set; }
    }
}
