//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALESCM
    {
        public int DocNum { get; set; }
        public int DocEntry { get; set; }
        public int InvLine { get; set; }
        public Nullable<int> TransID { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string Canceled { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public string CardCode { get; set; }
        public string DocType { get; set; }
        public Nullable<int> InvType { get; set; }
        public string LabNo { get; set; }
        public string WhsCode { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string CreditType { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string AcctCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ActTyp { get; set; }
        public Nullable<int> CYr { get; set; }
        public Nullable<int> CPd { get; set; }
        public Nullable<System.DateTime> RinDocDate { get; set; }
    }
}
