//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sapsetBck02062016
    {
        public string BID { get; set; }
        public string Code { get; set; }
        public string WhsName { get; set; }
        public string PriceCls { get; set; }
        public string PriceCls_Desc { get; set; }
        public string Customer { get; set; }
        public string IPAdd { get; set; }
        public string UID { get; set; }
        public string PWD { get; set; }
        public string LIS { get; set; }
        public string SOANo { get; set; }
        public string Pref { get; set; }
        public string IMG_IPAdd { get; set; }
        public Nullable<int> SortID { get; set; }
        public string Req_IPAdd { get; set; }
        public string wName { get; set; }
        public string TinNo { get; set; }
        public string Add1 { get; set; }
        public string TelNo { get; set; }
        public string BrAdd { get; set; }
        public string BrTin { get; set; }
        public string CorpName { get; set; }
        public string BType { get; set; }
        public string Blk { get; set; }
    }
}
