//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPSet
    {
        public string BID { get; set; }
        public string Code { get; set; }
        public string WhsName { get; set; }
        public string PriceCls { get; set; }
        public string PriceCls_Desc { get; set; }
        public string Customer { get; set; }
        public string IPAdd { get; set; }
        public string UID { get; set; }
        public string PWD { get; set; }
        public string LIS { get; set; }
        public string SOANo { get; set; }
        public string Pref { get; set; }
        public string IMG_IPAdd { get; set; }
        public Nullable<int> SortID { get; set; }
        public string Req_IPAdd { get; set; }
        public string wname { get; set; }
        public string TinNo { get; set; }
        public string Add1 { get; set; }
        public string TelNo { get; set; }
        public string BrAdd { get; set; }
        public string BrTin { get; set; }
        public string CorpName { get; set; }
        public string BType { get; set; }
        public string Blk { get; set; }
        public string Stat { get; set; }
        public string PEIP { get; set; }
        public string LabNo { get; set; }
        public string OfficeHrs { get; set; }
        public string Accenture { get; set; }
        public string GrpBrnch { get; set; }
        public string SSSNo { get; set; }
        public string PhilHlthNo { get; set; }
        public string PreparedBy { get; set; }
        public string CheckedBy { get; set; }
        public string Approvedby { get; set; }
        public string NotedBy { get; set; }
        public string PagIbigNo { get; set; }
        public string ZipCode { get; set; }
        public string Abref { get; set; }
        public string City { get; set; }
        public string BrWSPwd { get; set; }
        public string MissionIP { get; set; }
        public string LIS_MISSION_IP { get; set; }
        public string LIS_MISSION_BID { get; set; }
        public string HcLabIPAdd { get; set; }
        public string HcLabDNS { get; set; }
        public string Rq_branchReg { get; set; }
        public string SlsStat { get; set; }
        public string Biller { get; set; }
        public Nullable<int> POstat { get; set; }
        public string LISBrCode { get; set; }
        public string MotherBr { get; set; }
        public string AssetUName { get; set; }
        public string HistoBr { get; set; }
        public string DBoxPath { get; set; }
        public Nullable<int> IMGStat { get; set; }
        public string QuadStat { get; set; }
        public string billerName { get; set; }
        public Nullable<int> SSROrdr { get; set; }
        public string SSRStat { get; set; }
        public Nullable<int> IBSort { get; set; }
        public string IBStat { get; set; }
        public Nullable<int> CommSortID { get; set; }
        public Nullable<int> VatExempt { get; set; }
        public string LisGrp { get; set; }
        public string WinPwd { get; set; }
        public string RadPwd { get; set; }
        public Nullable<int> RbWhsGrp { get; set; }
        public string HasDRC { get; set; }
        public string CommStat { get; set; }
        public string CommColumn { get; set; }
        public string MissionIPNew { get; set; }
        public string CASHInc { get; set; }
        public string CcardInc { get; set; }
        public string AOPInc { get; set; }
        public string PFGPInc { get; set; }
        public string PFIMGInc { get; set; }
        public string BrType { get; set; }
        public Nullable<int> WHS_NetTax { get; set; }
        public Nullable<int> ComSort { get; set; }
        public string HSPurpose { get; set; }
        public Nullable<int> R { get; set; }
        public Nullable<int> G { get; set; }
        public Nullable<int> B { get; set; }
        public string PFGross { get; set; }
        public string ARInc { get; set; }
        public Nullable<int> InvWhs { get; set; }
        public string LISPwd { get; set; }
        public string POSPwd { get; set; }
        public string Rb_GrpBrnch { get; set; }
        public string UPaidInc { get; set; }
        public string OModeInc { get; set; }
        public string PFOfcr { get; set; }
    }
}
