//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCCompany
    {
        public string EmpComName { get; set; }
        public string BranchCode { get; set; }
        public string AcctNo { get; set; }
        public string IDHeader { get; set; }
        public string BIR_Branch { get; set; }
        public string BIR_RDO { get; set; }
        public string CompAdd { get; set; }
        public Nullable<int> TradeCode { get; set; }
    }
}
