//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scemptransdtl_Bak
    {
        public int DocEntry { get; set; }
        public string EmpCode { get; set; }
        public string TransType { get; set; }
        public string OldDtl { get; set; }
        public string NewDtl { get; set; }
        public System.DateTime EffDate { get; set; }
        public string Remarks { get; set; }
        public string LogUser { get; set; }
        public System.DateTime LogDate { get; set; }
        public string LogIPAdd { get; set; }
        public string Stat { get; set; }
        public string Sync { get; set; }
    }
}
