//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCEmpEducBck
    {
        public int DocEntry { get; set; }
        public string EmpCode { get; set; }
        public string Level { get; set; }
        public string School { get; set; }
        public Nullable<System.DateTime> SFrom { get; set; }
        public Nullable<System.DateTime> STo { get; set; }
        public string Course { get; set; }
        public string Received { get; set; }
    }
}
