//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCEmp_TK
    {
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string BranchCode { get; set; }
        public string DeptCode { get; set; }
        public string SecCode { get; set; }
        public byte[] EmpPic { get; set; }
    }
}
