//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCEmpaa
    {
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public Nullable<System.DateTime> DateResigned { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string EmpSex { get; set; }
        public string CivilStat { get; set; }
        public string EmpConNum { get; set; }
        public string EmpAddress { get; set; }
        public string EmpEduc { get; set; }
        public string EmpPBirth { get; set; }
        public string EmpBoard { get; set; }
        public string EmpPComName { get; set; }
        public string EmpPComAdd { get; set; }
        public string EmpPComCon { get; set; }
        public string EmpEConName { get; set; }
        public string EmpEConRel { get; set; }
        public string EmpEConNum { get; set; }
        public string EmpEConAdd { get; set; }
        public string BranchCode { get; set; }
        public int DeptCode { get; set; }
        public int SecCode { get; set; }
        public string Position { get; set; }
        public string EmpType { get; set; }
        public string EmpStat { get; set; }
        public string EmpMode { get; set; }
        public string EmpComName { get; set; }
        public string EmpAccNo { get; set; }
        public string SSSNo { get; set; }
        public string TINNo { get; set; }
        public string PAGIBIGNo { get; set; }
        public string PHILHEALTHNo { get; set; }
        public Nullable<bool> NBICle { get; set; }
        public Nullable<bool> POLICECle { get; set; }
        public Nullable<int> EmpPComTenure { get; set; }
        public Nullable<System.DateTime> DateReg { get; set; }
        public string TaxStatus { get; set; }
        public string EmpRank { get; set; }
        public string Outlook { get; set; }
        public string EmpStAdd { get; set; }
        public string EmpStateAdd { get; set; }
        public string EmpCityAdd { get; set; }
        public string Email { get; set; }
        public string Course { get; set; }
        public string ClsRate { get; set; }
    }
}
