//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCEmpAllow
    {
        public string EmpCode { get; set; }
        public Nullable<decimal> FoodAllow { get; set; }
        public string FoodAllowMode { get; set; }
        public Nullable<decimal> TransAllow { get; set; }
        public string TransAllowMode { get; set; }
        public Nullable<decimal> CellAllow { get; set; }
        public string CellAllowMode { get; set; }
        public string PhoneSim { get; set; }
    }
}
