//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCEngSrvyArchive
    {
        public string EmpCode { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<int> JS1 { get; set; }
        public Nullable<int> JS2 { get; set; }
        public Nullable<int> JS3 { get; set; }
        public Nullable<int> JS4 { get; set; }
        public Nullable<int> JS5 { get; set; }
        public Nullable<int> JS6 { get; set; }
        public Nullable<int> JS7 { get; set; }
        public Nullable<int> WE1 { get; set; }
        public Nullable<int> WE2 { get; set; }
        public Nullable<int> WE3 { get; set; }
        public Nullable<int> WE4 { get; set; }
        public Nullable<int> WE5 { get; set; }
        public Nullable<decimal> ER1 { get; set; }
        public string ER2 { get; set; }
        public string ER2Rmrk { get; set; }
        public Nullable<bool> ERConEdu { get; set; }
        public Nullable<bool> ERGoAbrd { get; set; }
        public Nullable<bool> ERGrnPas { get; set; }
        public Nullable<bool> ERHlthProb { get; set; }
        public Nullable<bool> ERManager { get; set; }
        public Nullable<bool> ERPeerCon { get; set; }
        public Nullable<bool> ERSprvsr { get; set; }
        public Nullable<bool> ERTakeBrd { get; set; }
        public Nullable<bool> ERWrkAnther { get; set; }
        public string EROther { get; set; }
        public Nullable<bool> WA1Bnfits { get; set; }
        public Nullable<bool> WA1Career { get; set; }
        public Nullable<bool> WA1CompStab { get; set; }
        public Nullable<bool> WA1MgmtSprt { get; set; }
        public Nullable<bool> WA1Manger { get; set; }
        public Nullable<bool> WA1PerfRcgn { get; set; }
        public Nullable<bool> WA1RelPeer { get; set; }
        public Nullable<bool> WA1Sprvsr { get; set; }
        public Nullable<bool> WA1Training { get; set; }
        public Nullable<bool> WA1TeamColl { get; set; }
        public Nullable<bool> WA1WrkCond { get; set; }
        public string WA1Other { get; set; }
        public Nullable<bool> WA2Manual { get; set; }
        public Nullable<bool> WA2NoEndo { get; set; }
        public Nullable<bool> WA2PeerWrk { get; set; }
        public Nullable<bool> WA2WrkCond { get; set; }
        public Nullable<bool> WA2WrkEnvi { get; set; }
        public Nullable<bool> WA2WrkSched { get; set; }
        public string WA2Other { get; set; }
        public string WA3MgmtSprt { get; set; }
        public string WA3Training { get; set; }
        public string WA3WrkEnvi { get; set; }
        public string WA3TaskRsp { get; set; }
        public string WA3Benefits { get; set; }
    }
}
