//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCExtIntv_Archive
    {
        public string EmpCode { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string Reason { get; set; }
        public string Q1 { get; set; }
        public string Q2 { get; set; }
        public string Q3 { get; set; }
        public string Q4 { get; set; }
        public string Q5 { get; set; }
        public string Q6 { get; set; }
        public string Q7 { get; set; }
        public string Q8 { get; set; }
        public string Q9a { get; set; }
        public string Q9b { get; set; }
        public string Q9c { get; set; }
        public string Q9d { get; set; }
        public string Share { get; set; }
        public string Comments { get; set; }
        public string Interviewer { get; set; }
        public Nullable<System.DateTime> IntrvwDate { get; set; }
        public string Status { get; set; }
    }
}
