//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCGP
    {
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string BranchOut { get; set; }
        public string EmpCode { get; set; }
        public string Reason { get; set; }
        public string SReason { get; set; }
        public string Remarks { get; set; }
        public bool Returned { get; set; }
        public Nullable<System.DateTime> TimeReturned { get; set; }
        public string Stat { get; set; }
        public string SupRemarks { get; set; }
        public Nullable<System.DateTime> BreakOut { get; set; }
        public Nullable<System.DateTime> BreakIn { get; set; }
    }
}
