//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedProc
    {
        public int Docentry { get; set; }
        public string Program { get; set; }
        public string Form { get; set; }
        public string btnName { get; set; }
        public string ProcDesc { get; set; }
        public Nullable<int> stat { get; set; }
        public Nullable<int> Start { get; set; }
        public Nullable<int> End { get; set; }
    }
}
