//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScholarReq
    {
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string EmpCode { get; set; }
        public string ScholCode { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public string Relation { get; set; }
        public string School { get; set; }
        public string Level { get; set; }
        public string Course { get; set; }
        public string Sem { get; set; }
        public Nullable<decimal> GWA { get; set; }
        public Nullable<decimal> TotFee { get; set; }
        public Nullable<decimal> ExFee { get; set; }
        public Nullable<decimal> Books { get; set; }
        public Nullable<decimal> DscntAmt { get; set; }
        public Nullable<decimal> PaidAmt { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string PayeeName { get; set; }
        public string PayeeSchool { get; set; }
        public string ReqBC { get; set; }
        public string ReqRC { get; set; }
        public string ReqAF { get; set; }
        public string ReqStat { get; set; }
        public Nullable<decimal> Entitlement { get; set; }
        public string AppBy { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public string CheckBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string ChkNoSchool { get; set; }
        public string ChkNoEmp { get; set; }
    }
}
