//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHoliday
    {
        public int DocEntry { get; set; }
        public string Date { get; set; }
        public string Description { get; set; }
        public string Transf { get; set; }
        public string Type { get; set; }
        public Nullable<int> Percent { get; set; }
        public string WeekDay { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
