//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCOc
    {
        public string OCCode { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public string DocResume { get; set; }
        public string DocApp { get; set; }
        public string DocPRC { get; set; }
    }
}
