//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCPosSlry
    {
        public int ID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public decimal BscSlry { get; set; }
        public Nullable<decimal> ECOLA { get; set; }
        public Nullable<decimal> OA { get; set; }
    }
}
