//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrapUserLog
    {
        public int docentry { get; set; }
        public string empid { get; set; }
        public string empname { get; set; }
        public string error { get; set; }
        public string ip { get; set; }
        public string @fixed { get; set; }
        public string errtype { get; set; }
    }
}
