//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCTimeProb
    {
        public string EmpCode { get; set; }
        public System.DateTime DocDate { get; set; }
        public string Typ { get; set; }
        public string RTIN { get; set; }
        public string RTOUT { get; set; }
        public string BranchName { get; set; }
    }
}
