//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDForm
    {
        public int Docentry { get; set; }
        public string Empcode { get; set; }
        public string cntno { get; set; }
        public string Remarks { get; set; }
        public string SupEmpcode { get; set; }
        public Nullable<System.DateTime> SupStatDate { get; set; }
        public string Stat { get; set; }
        public Nullable<int> DL { get; set; }
        public Nullable<int> ct { get; set; }
        public Nullable<int> er { get; set; }
        public Nullable<int> wt { get; set; }
        public Nullable<int> de { get; set; }
        public Nullable<int> S { get; set; }
        public string o { get; set; }
        public Nullable<System.DateTime> datereq { get; set; }
    }
}
