//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SprintTask
    {
        public int Id { get; set; }
        public Nullable<int> SprintId { get; set; }
        public string Title { get; set; }
        public Nullable<int> Type { get; set; }
        public string Description { get; set; }
        public string AssignTo { get; set; }
        public Nullable<decimal> OriHr { get; set; }
        public Nullable<decimal> RemHr { get; set; }
        public Nullable<decimal> ComHr { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Activity { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
