//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncScemp
    {
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string FName { get; set; }
        public string WhsCode { get; set; }
        public Nullable<int> DeptCode { get; set; }
        public Nullable<short> SlpCode { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public Nullable<System.DateTime> DateResigned { get; set; }
        public Nullable<bool> isUpdated { get; set; }
    }
}
