//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCodeOpt
    {
        public int Opt_Docentry { get; set; }
        public string Opt_Name { get; set; }
        public Nullable<int> OrdrBy { get; set; }
    }
}
