//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_ITEM
    {
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string TI_CODE { get; set; }
        public string TI_NAME { get; set; }
        public string TI_OTHER_NAME { get; set; }
        public string TI_PRINT_NAME { get; set; }
        public string TI_TEST_GRP { get; set; }
        public string TI_CATEGORY { get; set; }
        public string TI_UNIT { get; set; }
        public string TI_DATA_TYPE { get; set; }
        public string TI_FORMULA_CODE { get; set; }
        public string TI_SPL_TYPE { get; set; }
        public string TI_REC_FLAG { get; set; }
        public string TI_DELTA_CHECK { get; set; }
        public string TI_SI_UNIT { get; set; }
        public string TI_SI_FACTOR { get; set; }
        public string TI_LEVEL { get; set; }
        public string TI_ORDER_ENABLE { get; set; }
        public string TI_OUTPUT_MASK { get; set; }
        public string TI_ANZ_ORDER { get; set; }
        public string TI_TRIGGER_FORMULA { get; set; }
        public string TI_TRIGGER_ITEM1 { get; set; }
        public string TI_TRIGGER_ITEM2 { get; set; }
        public string TI_TRIGGER_ITEM3 { get; set; }
        public string TI_TRIGGER_ITEM4 { get; set; }
        public string TI_TRIGGER_ITEM5 { get; set; }
        public string TI_DISP_SEQ { get; set; }
        public string TI_LINK_ITEM { get; set; }
        public string TI_LINK_NO { get; set; }
        public string TI_ITPV_FLAG { get; set; }
        public string TI_MRF_FLAG { get; set; }
        public string TI_TM_CODE { get; set; }
        public string TI_CTL_FLAG { get; set; }
        public string TI_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> TI_UPDATE_ON { get; set; }
        public string TI_FTR_TPL { get; set; }
        public string TI_STAT_TAT { get; set; }
        public string TI_ROUTINE_TAT { get; set; }
        public string TI_TRIGGER_FR { get; set; }
        public string TI_URGENT_TAT { get; set; }
        public string TI_ATTACHED_CMT { get; set; }
        public string TI_DFLT_VALUE { get; set; }
        public string TI_MB_TEST_GRP { get; set; }
        public string TI_MB_PC_TYPE { get; set; }
        public string TI_REORDER_CTL { get; set; }
        public string TI_TH_CODE { get; set; }
        public string TI_TH_SEQ { get; set; }
        public string TI_BB_PC_TYPE { get; set; }
        public string TI_LABNO_SUFFIX { get; set; }
        public string TI_LONG_NAME { get; set; }
        public string TI_SPL_TYPE2 { get; set; }
        public string TI_QC_VALIDITY { get; set; }
        public string TI_MB_NOGROWTH_BR { get; set; }
        public string TI_MB_NOGROWTH_DAY { get; set; }
        public string TI_MB_NOGROWTH_CODE { get; set; }
        public string TI_MB_PRENOGROWTH_DAY { get; set; }
        public string TI_MB_PRENOGROWTH_CODE { get; set; }
        public string TI_ORDER_RETENTION { get; set; }
        public string TI_TB_CULTURE_FLAG { get; set; }
        public string TI_TB_NEGSTAIN_CODE { get; set; }
        public string TI_TB_MEDIA1 { get; set; }
        public string TI_TB_MEDIA1_CUTOFF { get; set; }
        public string TI_TB_MEDIA1_NOGROWTH_CODE { get; set; }
        public string TI_TB_MEDIA2 { get; set; }
        public string TI_TB_MEDIA2_CUTOFF { get; set; }
        public string TI_TB_MEDIA2_NOGROWTH_CODE { get; set; }
        public string TI_TB_MEDIA3 { get; set; }
        public string TI_TB_MEDIA3_CUTOFF { get; set; }
        public string TI_TB_MEDIA3_NOGROWTH_CODE { get; set; }
        public string TI_MIN_SPL_VOL { get; set; }
        public string TI_OPT_SPL_VOL { get; set; }
        public string TI_USE_PRIMARY_TUBE { get; set; }
        public Nullable<System.DateTime> DATE_DONE { get; set; }
        public Nullable<bool> STATUS_CREATED { get; set; }
    }
}
