//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestWeb
    {
        public int ID { get; set; }
        public byte[] ImgFile { get; set; }
        public string ImgType { get; set; }
        public string Size { get; set; }
    }
}
