//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLDtlTrx
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public string TaskDet { get; set; }
        public string BrCode { get; set; }
        public string EmpID { get; set; }
        public string Duration { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public Nullable<int> BaseNum { get; set; }
        public string stat { get; set; }
    }
}
