//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLHdrTrx
    {
        public int DocEntry { get; set; }
        public string Task { get; set; }
        public string BrCode { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string BaseEntry { get; set; }
        public string stat { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public Nullable<System.DateTime> DDate { get; set; }
        public Nullable<int> DeptCode { get; set; }
        public Nullable<int> SecCode { get; set; }
        public Nullable<decimal> Per { get; set; }
    }
}
