//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpSPLIST
    {
        public string SPD_CODE { get; set; }
        public string SPD_IMH_CODE { get; set; }
        public Nullable<decimal> SPD_CURR_PRICE { get; set; }
        public Nullable<System.DateTime> SPD_EFD { get; set; }
        public Nullable<decimal> SPD_PREV_PRICE { get; set; }
    }
}
