//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainCalendar
    {
        public Nullable<int> Yr { get; set; }
        public Nullable<int> Pd { get; set; }
        public string Dy { get; set; }
        public System.DateTime Dt { get; set; }
        public Nullable<int> Docentry { get; set; }
    }
}
