//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrxlogsTestCode_DET
    {
        public int Trxno { get; set; }
        public int LineNum { get; set; }
        public string Testcode { get; set; }
        public string Testname { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Whsname { get; set; }
        public string SvrIP { get; set; }
        public string ColUpdate { get; set; }
        public string Stat { get; set; }
    }
}
