//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tst_patient
    {
        public int PID { get; set; }
        public string PName { get; set; }
        public string PAdd { get; set; }
        public Nullable<int> SRId { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
        public string SRName { get; set; }
    }
}
