//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdCol_SAMPLE_TYPE
    {
        public int DOCENTRY { get; set; }
        public string ST_CODE { get; set; }
        public string ST_NAME { get; set; }
        public string ST_SG_CODE { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> Created_on { get; set; }
        public string Created_by { get; set; }
    }
}
