//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdCol_POS_AUTOMATIC_COMMENT
    {
        public int DOCENTRY { get; set; }
        public string AUTO_COMMENT_ID { get; set; }
        public string CREATED_BY { get; set; }
        public string UPDATED_BY { get; set; }
        public string CREATED_ON { get; set; }
        public string DATE_OF_EFFECTIVITY { get; set; }
        public string TI_CODE { get; set; }
        public string IS_VALID { get; set; }
        public string UPDATE_ON { get; set; }
        public string TI_COMMENT { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> CREATEDon { get; set; }
        public string CREATEDby { get; set; }
    }
}
