//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users2_backup20180328
    {
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public string SapID { get; set; }
        public string SapPwd { get; set; }
        public string LisID { get; set; }
        public string LisPwd { get; set; }
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public string WhsCode { get; set; }
        public string Dept { get; set; }
        public string Section { get; set; }
        public string UType { get; set; }
        public string Stat { get; set; }
        public string ReqUser { get; set; }
        public string ReqPWD { get; set; }
        public string BCODE { get; set; }
        public string EndOIC { get; set; }
        public string ManOIC { get; set; }
        public string ReqUtype { get; set; }
        public byte[] EPwd { get; set; }
        public string password { get; set; }
    }
}
