//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEEKLY_SLS_PER_SR
    {
        public int yr { get; set; }
        public int pd { get; set; }
        public int slpcode { get; set; }
        public string slpname { get; set; }
        public string cardcode { get; set; }
        public string cardname { get; set; }
        public string whscode { get; set; }
        public string hospital { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> sales { get; set; }
        public Nullable<decimal> paid { get; set; }
        public Nullable<decimal> Target { get; set; }
        public string District { get; set; }
    }
}
