//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkStation
    {
        public string IPAdd { get; set; }
        public string Hostname { get; set; }
        public string WhsCode { get; set; }
        public string EmpCode { get; set; }
        public string UserID { get; set; }
        public string Pwd { get; set; }
        public string Drive { get; set; }
    }
}
