//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yearlyeval
    {
        public string docentry { get; set; }
        public string empcode { get; set; }
        public string supempcode { get; set; }
        public string mgmtempcode { get; set; }
        public int eval_1_a { get; set; }
        public int eval_1_b { get; set; }
        public int eval_1_c { get; set; }
        public int eval_1_d { get; set; }
        public int eval_1_e { get; set; }
        public int eval_2 { get; set; }
        public int eval_3_a { get; set; }
        public int eval_3_b { get; set; }
        public int eval_3_c { get; set; }
        public int eval_3_d { get; set; }
        public int eval_3_e { get; set; }
        public int eval_4_a { get; set; }
        public int eval_4_b { get; set; }
        public int eval_5 { get; set; }
        public string ratecom_a { get; set; }
        public string ratecom_b { get; set; }
        public string ratecom_c { get; set; }
        public string ratecom_d { get; set; }
        public string empremarks { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
