//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcsLvl1
    {
        public string EmpID { get; set; }
        public string Program { get; set; }
        public string AccessLvl { get; set; }
        public string Category { get; set; }
    }
}
