//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALABANG_008_SCOic_20180706
    {
        public int OICCode { get; set; }
        public string EmpCode { get; set; }
        public string BranchCode { get; set; }
        public string DeptCode { get; set; }
        public string SecCode { get; set; }
        public string OutLook { get; set; }
    }
}
