//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALULDtl
    {
        public System.DateTime Date { get; set; }
        public string EmpID { get; set; }
        public int Ln { get; set; }
        public string ALUL { get; set; }
        public Nullable<byte> isALUL { get; set; }
        public string AlulReason { get; set; }
        public string Leave { get; set; }
        public Nullable<decimal> LvCnt { get; set; }
        public string LvReason { get; set; }
        public string Others { get; set; }
    }
}
