//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantStat
    {
        public System.DateTime DocDate { get; set; }
        public string Position { get; set; }
        public Nullable<int> Cnt { get; set; }
        public string Typ { get; set; }
        public string LogID { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
