//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantDet
    {
        public int AppCode { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string NName { get; set; }
        public string SName { get; set; }
        public string Position { get; set; }
        public string CityAdd { get; set; }
        public string ProvAdd { get; set; }
        public string CityCon { get; set; }
        public string ProvCon { get; set; }
        public string Living { get; set; }
        public string SSSNo { get; set; }
        public string TINNo { get; set; }
        public string PhilhealthNo { get; set; }
        public string PagibigNo { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string PlaceBirth { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public string Citizenship { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string EmailAdd { get; set; }
        public string CivilStatus { get; set; }
        public string SpouseName { get; set; }
        public Nullable<System.DateTime> SpouseBDate { get; set; }
        public string SpouseOcc { get; set; }
        public string SpouseComp { get; set; }
        public Nullable<int> NoOfChild { get; set; }
        public string MedicalHist { get; set; }
        public string BoardTitle { get; set; }
        public Nullable<int> IQ { get; set; }
        public Nullable<int> Purdue { get; set; }
        public string Encoding { get; set; }
        public string EName { get; set; }
        public string EAdd { get; set; }
        public string ERelation { get; set; }
        public string EContact { get; set; }
        public string HiringSource { get; set; }
        public string HiringEmp { get; set; }
        public string HiringEmpRel { get; set; }
        public Nullable<int> Punctuality { get; set; }
        public Nullable<int> Commitment { get; set; }
        public Nullable<int> Accuracy { get; set; }
        public string CName1 { get; set; }
        public string CAddNo1 { get; set; }
        public string COccu1 { get; set; }
        public Nullable<int> CYear1 { get; set; }
        public string CName2 { get; set; }
        public string CAddNo2 { get; set; }
        public string COccu2 { get; set; }
        public Nullable<int> CYear2 { get; set; }
        public string CName3 { get; set; }
        public string CAddNo3 { get; set; }
        public string COccu3 { get; set; }
        public Nullable<int> CYear3 { get; set; }
        public string ExpectPay { get; set; }
        public string NextPlan { get; set; }
        public string Abroad { get; set; }
        public string Commute { get; set; }
        public string Job { get; set; }
        public string Personality { get; set; }
        public string AppStatus { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string LivingType { get; set; }
        public string EmpStAdd { get; set; }
        public string EmpStateAdd { get; set; }
        public string EmpCityAdd { get; set; }
        public string EmpCode { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public string EncWPM { get; set; }
        public string EncPRCNT { get; set; }
        public Nullable<int> PosFam { get; set; }
        public string SpouseAdd { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DateTagHired { get; set; }
    }
}
