//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantDeploy
    {
        public string EmpCode { get; set; }
        public Nullable<System.DateTime> TentaDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DeployDate { get; set; }
        public string TrainDays { get; set; }
        public string WorkDays { get; set; }
        public string WorkHrs { get; set; }
    }
}
