//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSiteLog
    {
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string App { get; set; }
        public string MgmtStat { get; set; }
        public string MgmtCode { get; set; }
        public string EmpCode { get; set; }
        public string Remarks { get; set; }
        public string IpAdd { get; set; }
    }
}
