//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditreportcardlog
    {
        public string pd { get; set; }
        public int docentry { get; set; }
        public string ttype { get; set; }
        public string emp { get; set; }
        public Nullable<System.DateTime> tdt { get; set; }
    }
}
