//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditreportcardgoal
    {
        public int docentry { get; set; }
        public string Goals { get; set; }
        public string Criteria { get; set; }
        public string Createdby { get; set; }
        public string Dept { get; set; }
        public string sec { get; set; }
        public string GoalGrp { get; set; }
        public string createddate { get; set; }
        public string deptgrp { get; set; }
        public string GID { get; set; }
        public string Assign1 { get; set; }
        public string Assign2 { get; set; }
    }
}
