//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BGFrzReq
    {
        public int BGFRId { get; set; }
        public string EmpCode { get; set; }
        public string Yr { get; set; }
        public Nullable<decimal> OrigBal { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Additional { get; set; }
        public Nullable<decimal> NewBalance { get; set; }
        public string BGFRStat { get; set; }
        public string ReqBy { get; set; }
        public System.DateTime DateReq { get; set; }
        public string AppBy { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public string Remarks { get; set; }
    }
}
