//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIChangeAmt
    {
        public int DocEntry { get; set; }
        public string EmpCode { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> OrigAmt { get; set; }
        public Nullable<decimal> NewAmt { get; set; }
        public string Source { get; set; }
        public string Stat { get; set; }
        public string Remarks { get; set; }
        public string RequestBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
    }
}
