//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiGenReq
    {
        public int GenID { get; set; }
        public string EmpCode { get; set; }
        public int Yr { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Additional { get; set; }
        public Nullable<decimal> NewBalance { get; set; }
        public Nullable<decimal> OrigBal { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<System.DateTime> Sdate { get; set; }
        public Nullable<System.DateTime> Edate { get; set; }
        public string ReqStat { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public string ReqEmpCode { get; set; }
    }
}
