//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrGoal
    {
        public string labno { get; set; }
        public string EmpName { get; set; }
        public string whscode { get; set; }
        public Nullable<int> Yr { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<int> Mnth { get; set; }
        public string Reason { get; set; }
        public string Type { get; set; }
        public string WhsName { get; set; }
        public string TransType { get; set; }
        public string LOAType { get; set; }
        public string CMDMno { get; set; }
        public string Category { get; set; }
        public string Uploader { get; set; }
    }
}
