//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColBranch
    {
        public int DocEntry { get; set; }
        public string WhsCode { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public Nullable<System.DateTime> CollDate { get; set; }
        public string Bank { get; set; }
        public string Remarks { get; set; }
        public string Stat { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string PType { get; set; }
        public Nullable<int> Import { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string MixPMode { get; set; }
        public string Scheduled { get; set; }
        public Nullable<int> CTDoc { get; set; }
        public Nullable<int> PassBook { get; set; }
        public string CollRem { get; set; }
        public string Cancel { get; set; }
        public string CancelReason { get; set; }
        public Nullable<int> Infraction { get; set; }
        public string InfReason { get; set; }
        public string DMBank { get; set; }
    }
}
