//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coltrack1
    {
        public int DocEntry { get; set; }
        public int LineID { get; set; }
        public string CheckNo { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ApDocNo { get; set; }
        public string Remarks { get; set; }
        public string Verified { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ChkTyp { get; set; }
        public string Seperated { get; set; }
        public Nullable<int> QRSAP { get; set; }
        public Nullable<int> QRLine { get; set; }
        public string Recv { get; set; }
        public Nullable<System.DateTime> RecvDate { get; set; }
        public string AllowEdit { get; set; }
        public string Branch { get; set; }
    }
}
