//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustodLog
    {
        public int Docentry { get; set; }
        public string Vendor { get; set; }
        public string Whscode { get; set; }
        public string Department { get; set; }
        public string AcctNo { get; set; }
        public string MobileNo { get; set; }
        public string CustodianID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string typ { get; set; }
        public string triggerBy { get; set; }
    }
}
