//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashBoardMaint
    {
        public Nullable<int> Docentry { get; set; }
        public string Blk { get; set; }
        public string Code { get; set; }
        public string Program { get; set; }
        public string FunctionName { get; set; }
        public int Counts { get; set; }
    }
}
