//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dauditIT
    {
        public int docentry { get; set; }
        public string program { get; set; }
        public string enchacement { get; set; }
        public string stat { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public string reqby { get; set; }
        public string progtask { get; set; }
        public string announcement { get; set; }
        public string encodedby { get; set; }
        public string dtype { get; set; }
        public string tm { get; set; }
        public Nullable<System.DateTime> donedt { get; set; }
        public string suggestion { get; set; }
        public string sugby { get; set; }
    }
}
