//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DENRFILEtest
    {
        public int Docentry { get; set; }
        public int Ln { get; set; }
        public string DocName { get; set; }
        public byte[] DocFile { get; set; }
        public string DocPath { get; set; }
        public string DocExt { get; set; }
    }
}
