//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DENRLOG
    {
        public int Docentry { get; set; }
        public string Process { get; set; }
        public string DocName { get; set; }
        public string IsHdr { get; set; }
        public string IpAdd { get; set; }
        public string PCName { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
    }
}
