//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRTagged
    {
        public string DrCode { get; set; }
        public string ProgName { get; set; }
        public string ItemGroup { get; set; }
        public string DCode { get; set; }
        public string BranchCode { get; set; }
    }
}
