//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTPROG
    {
        public int Docentry { get; set; }
        public Nullable<System.DateTime> Docdate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string Developer { get; set; }
        public string Program { get; set; }
        public string SupProg { get; set; }
    }
}
