//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECred
    {
        public string Branchcode { get; set; }
        public string Typ { get; set; }
        public string SHORTCODE { get; set; }
        public string EmpComName { get; set; }
    }
}
