//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp201Files
    {
        public string EmpCode { get; set; }
        public Nullable<bool> CA { get; set; }
        public Nullable<bool> AF { get; set; }
        public Nullable<bool> Res { get; set; }
        public Nullable<bool> TOR { get; set; }
        public Nullable<bool> PRCCert { get; set; }
        public Nullable<bool> PRCRate { get; set; }
        public Nullable<bool> PRCId { get; set; }
        public Nullable<bool> PTR { get; set; }
        public Nullable<bool> Diploma { get; set; }
        public Nullable<bool> TC { get; set; }
        public Nullable<bool> EQ { get; set; }
        public Nullable<bool> SSS { get; set; }
        public Nullable<bool> PH { get; set; }
        public Nullable<bool> PB { get; set; }
        public Nullable<bool> BIR { get; set; }
        public Nullable<bool> PE { get; set; }
        public Nullable<bool> EVAL { get; set; }
        public Nullable<bool> AA { get; set; }
        public Nullable<bool> EC { get; set; }
        public Nullable<bool> ACK { get; set; }
    }
}
