//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPChangeID
    {
        public int DocEntry { get; set; }
        public string TblName { get; set; }
        public string Fld { get; set; }
        public string vFrom { get; set; }
        public string vTo { get; set; }
        public string IPAdd { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
