//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpCert
    {
        public string EmpCode { get; set; }
        public Nullable<bool> ASCTrain { get; set; }
        public Nullable<System.DateTime> ASCDateIss { get; set; }
        public Nullable<System.DateTime> ASCDateExp { get; set; }
        public Nullable<int> ASCCopy { get; set; }
        public Nullable<bool> DTTrain { get; set; }
        public Nullable<System.DateTime> DTDateIss { get; set; }
        public Nullable<System.DateTime> DTDateExp { get; set; }
        public Nullable<int> DTCopy { get; set; }
        public Nullable<bool> HIVTrain { get; set; }
        public Nullable<System.DateTime> HIVDateIss { get; set; }
        public Nullable<System.DateTime> HIVDateExp { get; set; }
        public Nullable<int> HIVCopy { get; set; }
        public Nullable<int> RMT { get; set; }
        public Nullable<System.DateTime> RMTDateIss { get; set; }
        public Nullable<System.DateTime> RMTDateExp { get; set; }
        public Nullable<int> RMTCopy { get; set; }
        public Nullable<int> RRT { get; set; }
        public Nullable<System.DateTime> RRTDateIss { get; set; }
        public Nullable<System.DateTime> RRTDateExp { get; set; }
        public Nullable<int> RRTCopy { get; set; }
        public Nullable<bool> ASCCOE { get; set; }
        public Nullable<bool> DTCOE { get; set; }
        public Nullable<bool> HIVCOE { get; set; }
    }
}
