//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empcommend_20181028
    {
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string BranchCode { get; set; }
        public string DocFrom { get; set; }
        public string isFromPatient { get; set; }
        public string DocDetails { get; set; }
        public string Commendation { get; set; }
        public string EndorsedBy { get; set; }
        public string Pic1 { get; set; }
        public string Pic2 { get; set; }
    }
}
