//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTrainlistBAK
    {
        public int DocEntry { get; set; }
        public System.DateTime DocDate { get; set; }
        public int EmpTCode { get; set; }
        public string TVenue { get; set; }
        public string TSpeaker { get; set; }
        public string TrainStat { get; set; }
        public string Attendees { get; set; }
        public Nullable<decimal> THours { get; set; }
        public string BranchCode { get; set; }
    }
}
