//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiredApplicantDet
    {
        public int UnoffAppCode { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string NName { get; set; }
        public string SName { get; set; }
        public string Position { get; set; }
        public string EmailAdd { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public Nullable<System.DateTime> TentaDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DeployDate { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public string EmpCode { get; set; }
        public Nullable<System.DateTime> datetaghired { get; set; }
    }
}
