//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HKAuditPic
    {
        public int DocEntry { get; set; }
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public string Position { get; set; }
        public string Dept { get; set; }
        public string Branch { get; set; }
        public Nullable<int> BrCode { get; set; }
    }
}
