//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HPD_PM
    {
        public int DocEntry { get; set; }
        public string EQUIPMENT_ID__ { get; set; }
        public string DESCRIPTION { get; set; }
        public string CURRENT_LOCATION { get; set; }
        public string CLASS { get; set; }
        public string BRANCH { get; set; }
        public string PM_SCHED { get; set; }
        public string del_unnecessary_files { get; set; }
        public string defrag { get; set; }
        public string scan_CPU_cleaning { get; set; }
        public string by_ { get; set; }
        public string note { get; set; }
    }
}
