//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRForm
    {
        public int DocEntry { get; set; }
        public string FormName { get; set; }
        public string FormDesc { get; set; }
        public string Emp { get; set; }
        public string Sup { get; set; }
        public string HR { get; set; }
    }
}
