//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_MASTERH
    {
        public string IMH_CODE { get; set; }
        public string WHSCODE { get; set; }
        public string IMH_DESC { get; set; }
        public string IMH_TYPE { get; set; }
        public string IMH_PDGROUP { get; set; }
        public string IMH_BILLCODE { get; set; }
        public string IMH_HOSTCODE { get; set; }
        public string IMH_STKUOM { get; set; }
        public string IMH_STKITEM_FLAG { get; set; }
        public string IMH_TAXABLE { get; set; }
        public Nullable<decimal> IMH_YTD_SQTY { get; set; }
        public Nullable<decimal> IMH_YTD_SAMT { get; set; }
        public Nullable<decimal> IMH_STD_COST { get; set; }
        public Nullable<decimal> IMH_CURR_P1 { get; set; }
        public Nullable<System.DateTime> IMH_EFD_P1 { get; set; }
        public Nullable<decimal> IMH_PREV_P1 { get; set; }
        public Nullable<decimal> IMH_CURR_P2 { get; set; }
        public Nullable<System.DateTime> IMH_EFD_P2 { get; set; }
        public Nullable<decimal> IMH_PREV_P2 { get; set; }
        public Nullable<decimal> IMH_CURR_P3 { get; set; }
        public Nullable<System.DateTime> IMH_EFD_P3 { get; set; }
        public Nullable<decimal> IMH_PREV_P3 { get; set; }
        public string IMH_FIXED_PRICE { get; set; }
        public string IMH_REC_FLAG { get; set; }
        public string IMH_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> IMH_UPDATE_ON { get; set; }
        public string IMH_INSURANCE_CODE { get; set; }
        public string IMH_DEPT_CODE { get; set; }
        public string TI_TEST_GRP { get; set; }
        public string APEPEME { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string SlsTyp { get; set; }
    }
}
