//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class J_SCDTR
    {
        public string EmpName { get; set; }
        public int IDNo { get; set; }
        public System.DateTime DocDate { get; set; }
        public string DocDay { get; set; }
        public System.DateTime TimeIn { get; set; }
        public System.DateTime BreakOut { get; set; }
        public System.DateTime BreakIn { get; set; }
        public System.DateTime LunchOut { get; set; }
        public System.DateTime LunchIn { get; set; }
        public System.DateTime BreakOut1 { get; set; }
        public System.DateTime BreakIn1 { get; set; }
        public System.DateTime TimeOut { get; set; }
        public Nullable<int> TotalTime { get; set; }
        public Nullable<int> TotalBreak { get; set; }
        public string FileName { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string WhsCode { get; set; }
        public string SheetName { get; set; }
    }
}
