//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_LIST
    {
        public int ID { get; set; }
        public string CLASS_NAME { get; set; }
        public string METHOD_NAME { get; set; }
        public string PARAMETER { get; set; }
        public string JOB_TYPE { get; set; }
        public string CRON { get; set; }
        public string IS_ACTIVE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    }
}
