//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAReq
    {
        public string CardCode { get; set; }
        public Nullable<int> AppCode { get; set; }
        public Nullable<int> DiagNosis { get; set; }
        public Nullable<int> PxSign { get; set; }
        public Nullable<int> DrSign { get; set; }
        public Nullable<int> Cost { get; set; }
        public string Others { get; set; }
        public Nullable<int> IsImage { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public string PDFFile { get; set; }
        public string ModBy { get; set; }
    }
}
