//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MixPmode
    {
        public int Docentry { get; set; }
        public string LabNo { get; set; }
        public string WhsCode { get; set; }
        public string PMode { get; set; }
        public Nullable<System.DateTime> TrxDate { get; set; }
        public string OrigPmode { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public int GenID { get; set; }
    }
}
