//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTTran
    {
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string LabNo { get; set; }
        public string PxName { get; set; }
        public string MTCode { get; set; }
        public string MTName { get; set; }
        public string WhsCode { get; set; }
        public string HSCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
