//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotUpdateCol
    {
        public int DocEntry { get; set; }
        public string BranchName { get; set; }
        public string IPAdd { get; set; }
        public string Testcode { get; set; }
        public string ColName { get; set; }
        public Nullable<bool> ColStatus { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateComplete { get; set; }
    }
}
