//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPDeduc
    {
        public int DeducEntry { get; set; }
        public int Ln { get; set; }
        public Nullable<System.DateTime> dtDeduc { get; set; }
        public Nullable<decimal> DeducAmt { get; set; }
        public string DeducPeriod { get; set; }
        public string DeducEmpCode { get; set; }
        public string Status { get; set; }
    }
}
