//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSLP
    {
        public short SlpCode { get; set; }
        public string SlpName { get; set; }
        public Nullable<short> GroupCode { get; set; }
        public string Locked { get; set; }
        public string DataSource { get; set; }
        public string District { get; set; }
        public Nullable<decimal> Target { get; set; }
        public string EmpCode { get; set; }
    }
}
