//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT
    {
        public int DocEntry { get; set; }
        public string EmpCode { get; set; }
        public System.DateTime DocDate { get; set; }
        public string WhsCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> TTime { get; set; }
    }
}
