//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ottag20150914
    {
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public System.DateTime DocDate { get; set; }
        public Nullable<decimal> OTTO { get; set; }
        public Nullable<decimal> OTTI { get; set; }
        public Nullable<decimal> NDOT { get; set; }
        public Nullable<decimal> RDOT { get; set; }
        public Nullable<decimal> TotOT { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public string ApprovedBy { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<System.DateTime> DateCancelled { get; set; }
        public string OTStat { get; set; }
        public Nullable<int> Docentry { get; set; }
    }
}
