//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCApprHist
    {
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> Docdate { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public string EmpID { get; set; }
        public string AppBy { get; set; }
        public string IPAdd { get; set; }
    }
}
