//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCFAcct
    {
        public string Expense { get; set; }
        public string AcctCode { get; set; }
        public string AcctName { get; set; }
        public string Rtype { get; set; }
        public string Stat { get; set; }
        public int ID { get; set; }
    }
}
