//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCFErrList
    {
        public int PID { get; set; }
        public Nullable<int> BrEntry { get; set; }
        public string Whscode { get; set; }
        public Nullable<int> Docentry { get; set; }
        public string TransDesc { get; set; }
        public string Custodian { get; set; }
        public string CustodName { get; set; }
        public Nullable<int> ErrID { get; set; }
        public Nullable<int> ErrCnt { get; set; }
        public string Others { get; set; }
        public Nullable<int> Ln { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<System.DateTime> TrxDate { get; set; }
        public Nullable<System.DateTime> ErrorDate { get; set; }
        public string Postby { get; set; }
    }
}
