//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCFlog
    {
        public int Docentry { get; set; }
        public Nullable<System.DateTime> Docdate { get; set; }
        public string process { get; set; }
        public string Error { get; set; }
        public string ipadd { get; set; }
        public string empid { get; set; }
        public string Form { get; set; }
    }
}
