//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PForm
    {
        public int DocEntry { get; set; }
        public int LineID { get; set; }
        public string ObjName { get; set; }
        public string ObjEvent { get; set; }
        public string ProcName { get; set; }
        public string Codes { get; set; }
    }
}
