//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRAddition
    {
        public int TransId { get; set; }
        public string EmpCode { get; set; }
        public string Code { get; set; }
        public string PdType { get; set; }
        public Nullable<decimal> AddTotal { get; set; }
        public Nullable<decimal> NoOfAdd { get; set; }
        public Nullable<decimal> Amortization { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
    }
}
