//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRAlu
    {
        public string DocEntry { get; set; }
        public string EmpCode { get; set; }
        public Nullable<int> ShouldBe { get; set; }
        public Nullable<int> Present { get; set; }
        public Nullable<decimal> Absnt { get; set; }
        public Nullable<int> Late { get; set; }
        public Nullable<int> UT { get; set; }
        public Nullable<int> LLunch { get; set; }
        public Nullable<int> LateMin { get; set; }
        public Nullable<decimal> UTMin { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<int> OTDays { get; set; }
        public Nullable<int> OTHours { get; set; }
        public Nullable<decimal> SBHour { get; set; }
        public Nullable<decimal> AbsHour { get; set; }
        public Nullable<decimal> DPres { get; set; }
        public Nullable<decimal> DPCola { get; set; }
        public Nullable<decimal> OTTI { get; set; }
        public Nullable<decimal> OTTO { get; set; }
        public Nullable<decimal> RDOT { get; set; }
        public Nullable<decimal> NDOT { get; set; }
        public Nullable<decimal> TotOT { get; set; }
        public Nullable<decimal> HOT { get; set; }
        public Nullable<int> LunchLateMin { get; set; }
        public Nullable<decimal> ND { get; set; }
    }
}
