//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceLvlNew
    {
        public string Pricelist { get; set; }
        public string OldPriceList { get; set; }
        public string PricelistName { get; set; }
        public string PriceLevel { get; set; }
        public Nullable<decimal> Regular { get; set; }
        public Nullable<decimal> Regular2 { get; set; }
        public Nullable<decimal> STest { get; set; }
        public Nullable<decimal> STest2 { get; set; }
        public Nullable<decimal> Imaging { get; set; }
        public Nullable<decimal> Imaging2 { get; set; }
        public Nullable<decimal> UTZ { get; set; }
        public Nullable<decimal> UTZ2 { get; set; }
    }
}
