//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProbEval
    {
        public string EmpCode { get; set; }
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string Evaluator { get; set; }
        public string EvalType { get; set; }
        public int JK { get; set; }
        public int QW { get; set; }
        public int PQ { get; set; }
        public int INT { get; set; }
        public int OS { get; set; }
        public int PSJ { get; set; }
        public int PRO { get; set; }
        public int TC { get; set; }
        public int ATT { get; set; }
        public int MD { get; set; }
        public string Strengths { get; set; }
        public string Improvement { get; set; }
        public string Remarks { get; set; }
        public string Recommendation { get; set; }
        public string Stat { get; set; }
    }
}
