//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgPrio
    {
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string ProgName { get; set; }
        public string Typ { get; set; }
        public string DueDate { get; set; }
        public string DateDone { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public string Programmer { get; set; }
        public string Remarks { get; set; }
    }
}
