//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PYEmp
    {
        public string EmpId { get; set; }
        public string SSSNo { get; set; }
        public string PhilHlthID { get; set; }
        public string PagIbigID { get; set; }
        public string TINno { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public Nullable<decimal> OA { get; set; }
        public Nullable<decimal> ECOLA { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string WhldCode { get; set; }
        public string WhldType { get; set; }
        public string WhldDesc { get; set; }
    }
}
