//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PyMsgrDed
    {
        public int DocEntry { get; set; }
        public string DducCode { get; set; }
        public string DducDes { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string type { get; set; }
    }
}
