//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PYMSSS
    {
        public int DocEntry { get; set; }
        public Nullable<decimal> Rmin { get; set; }
        public Nullable<decimal> Rmax { get; set; }
        public Nullable<decimal> EmpeShrd { get; set; }
        public Nullable<decimal> EmprShrd { get; set; }
    }
}
