//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report2
    {
        public string labnumber { get; set; }
        public string testcode { get; set; }
        public string testname { get; set; }
        public string Amt { get; set; }
        public string Category { get; set; }
        public string PID2 { get; set; }
        public string pkgCode { get; set; }
        public string whscode { get; set; }
    }
}
