//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesApp
    {
        public int BrEntry { get; set; }
        public string Whscode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<byte> SlsStat { get; set; }
    }
}
