//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_SLSPERSON
    {
        public int Yr { get; set; }
        public int Pd { get; set; }
        public int SlpCode { get; set; }
        public string SlpName { get; set; }
        public Nullable<decimal> NetAmt { get; set; }
        public Nullable<decimal> Target { get; set; }
        public string District { get; set; }
        public string MD { get; set; }
    }
}
