//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPDM
    {
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string LabNo { get; set; }
        public string CardCode { get; set; }
        public Nullable<System.DateTime> DateRec { get; set; }
        public string WhsCode { get; set; }
        public string PMode { get; set; }
        public string DMNo { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> Doctotal { get; set; }
        public string Stat { get; set; }
        public string Category { get; set; }
        public string Refno { get; set; }
        public string EmpId { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    }
}
