//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPDMa
    {
        public string Docentry { get; set; }
        public string LabNo { get; set; }
        public string WhsCode { get; set; }
        public string CardName { get; set; }
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public string CliID { get; set; }
        public string CliName { get; set; }
        public string Refno { get; set; }
    }
}
