//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCDr
    {
        public string DrCode { get; set; }
        public string DrName { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string SName { get; set; }
        public string BranchCode { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public string Position { get; set; }
        public Nullable<bool> Consultancy { get; set; }
        public Nullable<bool> Resident { get; set; }
        public Nullable<bool> Reliever { get; set; }
        public Nullable<bool> Renting { get; set; }
        public Nullable<bool> RContract { get; set; }
        public Nullable<bool> RContractNA { get; set; }
        public Nullable<bool> AppForm { get; set; }
        public Nullable<bool> CV { get; set; }
        public Nullable<bool> PrcBCert { get; set; }
        public Nullable<bool> PrcBRate { get; set; }
        public string PrcRegNo { get; set; }
        public Nullable<System.DateTime> PrcRegDate { get; set; }
        public Nullable<System.DateTime> PrcExpDate { get; set; }
        public Nullable<bool> Ptr { get; set; }
        public string TIN { get; set; }
        public Nullable<bool> PhlHealth { get; set; }
        public Nullable<bool> Diploma { get; set; }
        public Nullable<bool> TrainingCert { get; set; }
        public Nullable<System.DateTime> PrcBCertSub { get; set; }
        public Nullable<System.DateTime> PrcBRateSub { get; set; }
        public Nullable<System.DateTime> PhlHealthSub { get; set; }
        public Nullable<System.DateTime> TinSub { get; set; }
        public string Other1 { get; set; }
        public Nullable<System.DateTime> Other1Sub { get; set; }
        public string Other2 { get; set; }
        public Nullable<System.DateTime> Other2Sub { get; set; }
        public string Other3 { get; set; }
        public Nullable<System.DateTime> Other3Sub { get; set; }
        public string Other4 { get; set; }
        public Nullable<System.DateTime> Other4Sub { get; set; }
        public string Other5 { get; set; }
        public Nullable<System.DateTime> Other5Sub { get; set; }
        public Nullable<bool> HMO { get; set; }
        public Nullable<bool> MedExam { get; set; }
        public Nullable<decimal> Benefit { get; set; }
        public string civilstat { get; set; }
        public string PID { get; set; }
        public string ExEmpBen { get; set; }
        public Nullable<decimal> MIRate { get; set; }
        public string ATCCode { get; set; }
        public Nullable<decimal> ATCRate { get; set; }
        public Nullable<System.DateTime> DateResigned { get; set; }
        public string acctno { get; set; }
    }
}
