//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCEmpReqProf
    {
        public string EmpCode { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string EmpStAdd { get; set; }
        public string EmpCityAdd { get; set; }
        public string EmpStateAdd { get; set; }
        public string EmpPBirth { get; set; }
        public string EmpConNum { get; set; }
        public string EmpSex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string CivilStat { get; set; }
        public string TaxStatus { get; set; }
        public string EmpEduc { get; set; }
        public string EmpBoard { get; set; }
        public string EmpEConName { get; set; }
        public string EmpEConRel { get; set; }
        public string EmpEConNum { get; set; }
        public string EmpEConAdd { get; set; }
        public byte[] EmpImg { get; set; }
        public string OutLook { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public string Stat { get; set; }
        public Nullable<System.DateTime> StatDate { get; set; }
        public string Reason { get; set; }
    }
}
