//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCEmpTrainOut
    {
        public string EmpCode { get; set; }
        public string Training { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string Speaker { get; set; }
        public string Venue { get; set; }
    }
}
