//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCLeaveMon
    {
        public string EmpCode { get; set; }
        public string BrDept { get; set; }
        public string TypLeave { get; set; }
        public Nullable<int> NoOfPreg { get; set; }
        public System.DateTime DocStart { get; set; }
        public Nullable<System.DateTime> DocEnd { get; set; }
        public Nullable<System.DateTime> DocResume { get; set; }
    }
}
