//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCListLeg
    {
        public string Leg { get; set; }
        public string LegName { get; set; }
        public string LegDesc { get; set; }
        public string Mode { get; set; }
        public string Access { get; set; }
        public string Properties { get; set; }
        public string Method { get; set; }
    }
}
