//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCPrfx128
    {
        public string EmpComName { get; set; }
        public string Branchcode { get; set; }
        public string Brprfx { get; set; }
        public string DeptPrfx { get; set; }
    }
}
