//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCSection
    {
        public int SecCode { get; set; }
        public string SecName { get; set; }
        public int DeptCode { get; set; }
        public string SecPrfx { get; set; }
        public string SecPrfx128 { get; set; }
    }
}
