//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSSCont
    {
        public int Docentry { get; set; }
        public decimal SlryFrom { get; set; }
        public decimal SlryTo { get; set; }
        public decimal SSS { get; set; }
    }
}
