//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSample
    {
        public int docentry { get; set; }
        public string u_labno { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string WhsCode { get; set; }
    }
}
