//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipCode
    {
        public int id { get; set; }
        public string country { get; set; }
        public string major_area { get; set; }
        public string zip_code { get; set; }
        public string city { get; set; }
    }
}
